--------------------------------------------------Helper Suite Information-------------------------------------------

#https://github.cerner.com/EggPlant/IPDev-Shared-Millennium
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-Immunizations
------------------------------------------------------------------------------------------------------------------------------
params domain
set format to "%b %d, %Y"
set domain to "Immunizations/Util/Setup".domainRun(domain)
set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
set username to setup.username
set password to decodeText(setup.("password").trimAll, "HLM")
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set relationship to setup.relationship
set subMenu to setup.subMenu

set common to JSONValue(file resourcePath("Common.json"))
set menu to common.menu

set testData to JSONValue(file ResourcePath("TIMER/Abilities_Lab/testData.json"))
set dateFormat to testData.dateFormat

set testData to JSONValue(file ResourcePath("TIMER/Abilities_Lab/testData.json")).(text of domain)
set patientName to testData.patient1.nameFullFormatted
set dob to "Immunizations/Util/Date".adjustDate(testData.patient1.dob, format)
set vaccineName1 to testData.vaccineName1
set vaccineName2 to testData.vaccineName2
set vaccineName3 to testData.vaccineName3
set source to testData.source
set product to testData.product
set notGivenType to testData.notGivenType
set notGivenAction to testData.notGivenAction
set notGivenReason to testData.notGivenReason

set global cleanup to  "Immunizations/setup".setCleanup()

try 
	log "Util".stepNumber & "ACTION: Open Powerchart and navigate to Patient 1's chart."
	run "Immunizations/setup".LoginAndLoadcomponentViaMenu username, password, domain, patientName, menu, subMenu, global cleanup, relationship
	----------------------------------------------------------------------------------------------------------
	
	log "Util".stepNumber & "ACTION: Document an administration for "& vaccineName1 &"."
	run "Immunizations/Common/DocumentHistory/Task".documentRequiredInput vaccineName1, dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("month": 6)), source,"submit"
	----------------------------------------------------------------------------------------------------------
	
	log "Util".stepNumber & "ACTION: Document an administration for "& vaccineName2 &"."
	run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName2, dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("month": 6)), source, product, "submit"
	----------------------------------------------------------------------------------------------------------
	
	log "Util".stepNumber & "ACTION: Unchart "& vaccineName1 &"."
	run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName1
	run "Immunizations/WorkFlowMPage/SidePanel/Task".unchart "Immunizations/Util/Date".adjustDate(dob, format, ("month": 6)),1,"Mistake"
	----------------------------------------------------------------------------------------------------------
	
	log "Util".stepNumber & "ACTION: Document an Not Given for "& vaccineName3 &"."
	run "Immunizations/Common/ChartNotGiven/Task".chartRequiredInput vaccineName3, notGivenType, notGivenAction, notGivenReason, "Submit"
	----------------------------------------------------------------------------------------------------------
	
	log "Util".stepNumber & "ACTION: Click on the print record button."
	run "Immunizations/Common/Print/Actions".clickPrintRecord("Print Record")
	----------------------------------------------------------------------------------------------------------
catch exception
	logError "Exception encountered" && exception.reason
	log "Exception Location:" && exception.location	
	captureScreen"Exception" && "at" & Global stepNumber
end try

----------------------------------------------------------------------------------------------------------
log "Util".stepNumber &"ACTION: Close patient's chart."
run "Immunizations/setup".closeApplication global cleanup
--------------------------------------------------------------------------------------------------------------- 	