(* 

HELPER SUITE INFO: 
# https: //github.cerner.com/EggPlant/IPDev-mPages-Shared-Immunizations
# https: //github.cerner.com/EggPlant/IPDev-Shared-Millennium 
# https: //github.cerner.com/EggPlant/IPDev-Millennium-Shared-HealthMaintenanceTools
#https://github.cerner.com/EggPlant/IPDev-Shared-Utilities

RQM TEST SCRIPT LINK: 
# https://jazz.cerner.com:9443/qm/web/console/IP#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestScript&id=108815

*)
params domain

log "Test running in domain" && domain
set domain to "Immunizations/Util/Setup".domainRun(domain)

set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
set username to setup.username
set password to decodeText(setup.("password").trimAll, "HLM")
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set encounterorg to setup.encounterorg
set relationship to setup.relationship
set conversation to setup.conversation
set encounterType to setup.encounterType

set common to JSONValue(file resourcePath("common.json"))
set menu to common.menu
set subMenu to common.subMenu
set viewpoint to common.viewpoint
set doseInFocusImage to common.doseInFocusImage
set doubleDashImage to common.doubleDashImage

set textStrings to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("textStrings.json")),domain)
set inRange to textStrings.inRange
set viewForecast to textStrings.viewForecast
set notStarted to textStrings.notStarted
set due to textStrings.due
set earliestRecommendedWithoutColon to textStrings.earliestRecommendedWithoutColon
set inRangeToday to textStrings.inRangeToday
set complete to textStrings.complete
set notDueUntil to textStrings.notDueUntil
set administered to textStrings.administered
set printRecord to textStrings.printRecord

set fieldLabels to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("fieldLabels.json")),domain)
set minimum to fieldLabels.minimum
set earliestRecommended to fieldLabels.earliestRecommended
set latestRecommended to fieldLabels.latestRecommended
set maximum to fieldLabels.maximum

set testData to JSONValue(file resourcePath("VR/Meningococcal_Vaccine_Forecast/testData.json")).(value of domain)
set lastName to testData.Patient_Conditional_Skip.lastName
set firstName to testData.Patient_Conditional_Skip.firstName
set patientName to testData.Patient_Conditional_Skip.nameFullFormatted
set newLastName to testData.Patient_Conditional_Skip.newLastName
set sex to testData.Patient_Conditional_Skip.sex
set dob to formattedTime("%m/%d/%Y", value(testData.Patient_Conditional_Skip.dob))
set vaccineName to testData.vaccineName
set visLink1 to testData.visLink1
set product1 to testData.eventSet1
set Source to testData.Source

set format to "%b %d, %Y"


Try
	---------------------------------------------------------------------------------------------------------------
	# PATIENT SETUP
	Log "PATIENT CREATION: Open PmLaunch and Create patient(s) for the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, "%m/%d/%Y", dob, encounterType
	Run "Util".closeApplication 2
	
	----------------------------------------------------------------------------------------------------------------
	
	Try
		#################################################################################
		# TEST STEPS
		
		BeginTestCase "VR/Meningococcal/HLM-VR-Immunizations-Meningococcal_Vaccine_Forecast_Cond_Skip" 
		
		Log "Util".stepNumber & "ACTION: Ensure Patient 3's chart opens within Immunization workflow MPage and navigate to Immunization section."
		run "Immunizations/setup".loginAndLoadcomponentViaMenu username, password, domain, patientName, menu, subMenu,  relationship
		
		Log "VERIFICATION: Ensure the Immunization Workflow MPage displays." 
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameColumn vaccineName
		
		Log "VERIFICATION: Ensure meningococcal is displayed in Status column as 'In Range'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, inRange
		
		Log "VERIFICATION: Next Dose Recommended column as 'Today – Recommended Until date' (17 years + 4 weeks - 1 day)."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName, "Today" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 17, "Week": 4, "Day": -1))
		CaptureScreen(Name: "Step" & Global stepNumber & "-Dose 1 Validation_P5") 
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Immunization Forecaster."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast(viewForecast)
		
		Log "VERIFICATION: Ensure Under CDC schedule column Meningococcal display as 'Not Started' below vaccine group name."
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName & return & notStarted, columnSearchRectangle
		
		Log "VERIFICATION: Ensure Dose 1 displays from Today's column."
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyText "Dose 1", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		CaptureScreen(Name: "Step" & Global stepNumber & "-Forecaster Validation_P5") 
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Vaccine Header."
		run "Immunizations/Forecaster-Forecast/Actions".clickVaccineName vaccineName
		
		Log "VERIFICATION: Ensure the Vaccine Name under CDC Schedule expands and displays with Vaccine name and Not Started at the bottom."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneHeaderSearchRectangle()
		run "Immunizations/Util/Validation".verifyImage doseInFocusImage, rectangle
		run "Immunizations/Util/Validation".verifyText vaccineName & return & notStarted, rectangle
		
		Log "VERIFICATION: In the right-hand pane header, Dose 1 Due Today – Meningococcal displays at the top with the Recommended From (16 years days from DOB) - Recommended Until Date (17 years + 4 weeks - 1 day from DOB) and In Range Today."
		Set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
		Set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle 
		run "Immunizations/Util/Validation".verifyText "Dose 1" && due && "Today" && "-" && vaccineName, rightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText earliestRecommendedWithoutColon && "Immunizations/Util/Date".adjustDate(dob, "%m/%d/%y", ("Year": 16)) && "-" && "Immunizations/Util/Date".adjustDate(dob, "%m/%d/%y", ("Year": 17, "Week": 4, "Day": -1)), rightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText inRangeToday, rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Ensure Below onto right VIS link is available."
		run "Immunizations/Util/Validation".verifyText visLink1, rightPaneBodySearchRectangle
		CaptureScreen(Name: "Step" & Global stepNumber & "-Expanded View Validation_P5") 
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on the Dose 1 to open the expanded view"
		click text: "1", searchrectangle: "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchrectangle()
		
		Log "VERIFICATION: Ensure in the right-hand pane, the following details are displayed at the bottom."
		Set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText "Dose 1", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: 1. Earliest: 16 years from DOB"
		set dose1MinimumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 16))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField Minimum, dose1MinimumDate
		set dose1MinimumAge to "Immunizations/Util/Date".ageCalculator(dob, dose1MinimumDate, false, true)
		Set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle()
		Run "Immunizations/Util/Validation".verifyTextWithPattern dose1MinimumAge, "Immunizations/Util/Date".setPattern(dose1MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: 2. Recommended From: 16 years from DOB"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField EarliestRecommended, dose1MinimumDate
		Run "Immunizations/Util/Validation".verifyTextWithPattern dose1MinimumAge, "Immunizations/Util/Date".setPattern(dose1MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(EarliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: 3. Recommended Until: 17 years + 4 weeks - 1 day from DOB"
		set dose1LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 17, "Week": 4, "Day": -1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField LatestRecommended, dose1LatestRecommendedDate
		set dose1LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose1LatestRecommendedDate, false, true)
		Run "Immunizations/Util/Validation".verifyTextWithPattern dose1LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose1LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(LatestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: 4. Latest: 19 years - 1 day from DOB."
		set dose1MaximumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 19, "Day": -1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField Maximum, dose1MaximumDate
		set dose1MaximumAge to "Immunizations/Util/Date".ageCalculator(dob, dose1MaximumDate, false, true)
		Run "Immunizations/Util/Validation".verifyTextWithPattern dose1MaximumAge, "Immunizations/Util/Date".setPattern(dose1MaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(Maximum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Ensure in the left-hand pane, Dose 1 displays with a status of 'Due' at the top and Recommended from Age (16 years + 4 days from DOB) below it."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("1")
		run "Immunizations/Util/Validation".verifyText due & return & "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 16, "Day": 4)), rectangle
		CaptureScreen(Name: "Step" & Global stepNumber & "-ExpandViewDose1 Valid_P5") 
		--------------------------------------------------------------------------------------------------------------- 
		
		// 2 dose series: TRUE dose 1 set Id 1 (evaluation conditional skip)
		Log "Util".stepNumber & "ACTION: Exit out of the expanded view and Chart Dose 1 using Meningococcal Conjugate Vaccine as a product with administration dated as 16 years from DOB."
		Set topPaneRectangle to "Immunizations/Common/Helpers".tabListSearchrectangle
		Click text: printRecord, searchrectangle: topPaneRectangle
		set dose1AdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 16, "Day": -4))
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName, "Date", dose1AdminDate, Source, product1, "Submit"
		
		Log "VERIFICATION: Ensure the Dose 1 displays charted with product name on top along with the dose number and administration date dated 16 years - 4 days from DOB below it."
		Set startDateHeader to dose1AdminDate
		Set endDateHeader to dose1AdminDate
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader,  "-250", "-50", "80", "50")
		run "Immunizations/Util/Validation".verifyText product1 & return & "Dose 1" && "-" && dose1AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure CDC schedule column displays with a status of 'Complete' under Meningococcal Vaccine."
		Set columnSearchrectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName & return & complete, columnSearchRectangle
		CaptureScreen(Name: "Step" & Global stepNumber & "-Charted Dose 1 Validation_P5")
		--------------------------------------------------------------------------------------------------------------- 
		
		Log "Util".stepNumber & "ACTION: Click on Immunization workflow MPage."
		run "Immunizations/Common/Actions".clickMPagesView viewPoint
		
		Log "VERIFICATION: Verify Meningococcal Vaccine displays in History section with status 'Complete'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameColumn vaccineName
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameHistorySection vaccineName
		
		Log "VERIFICATION: Ensure the status for Meningococcal displays as complete."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, complete
		
		Log "VERIFICATION: Verify the Administrations displays 1."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, "1"
		
		Log "VERIFICATION: Verify Next Dose Recommended displays '--'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName, doubleDashImage
		
		Log "VERIFICATION: Verify Last Action column displays 'Administered'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionColumn vaccineName, administered
		
		Log "VERIFICATION: Verify Last Action Date column displays with the last charting event date."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionDateColumn vaccineName, uppercase(dose1AdminDate), "Immunizations/Util/Date".ageCalculator(dob, dose1AdminDate, false, false)
		CaptureScreen(Name: "Step" & Global stepNumber & "-WorkFlow MPage Validation_P5") 
		--------------------------------------------------------------------------------------------------------------- 
		
		Log "Util".stepNumber & "ACTION: Unchart Dose 1 for Meningococcal."
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName
		run "Immunizations/WorkflowMPage/SidePanel/Task".unchart dose1AdminDate, "1", "test"
		
		Log "VERIFICATION: Ensure the status for Meningococcal displays as 'In Range'.'"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, inRange
		CaptureScreen(Name: "Step" & Global stepNumber & "-WFMPage Unchart Valid_P5")
		--------------------------------------------------------------------------------------------------------------- 
		
		Log "Util".stepNumber & "ACTION: Click on the '+' button, select document history and chart Dose 1 at 15 years + 11 months from DOB and navigate to Immunization Forecaster."
		set dose1NewAdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 15, "Month": 11))
		run "Immunizations/Common/DocumentHistory/Task".documentRequiredInput vaccineName, "Date", dose1NewAdminDate, Source, "Submit"
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast(viewForecast)
		
		Log "VERIFICATION: Ensure Dose 1 displays charted in the time line with Product name on the top and Dose number and administration date dated for 15 years +11 months from DOB below it."
		Set startDateHeader to dose1NewAdminDate
		Set endDateHeader to dose1NewAdminDate
		Set rowSearchrectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader,  "-150", "-50", "130", "50")
		run "Immunizations/Util/Validation".verifyText product1 & return & "Dose 1" && "-" && dose1NewAdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure Dose 2 displays 8 weeks from dose 1 within the timeline."
		run "Immunizations/Util/Validation".validationJiraComment "HMDEV-2045"
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dose1NewAdminDate, format, ("Week": 8))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 17, "Week": 4, "Day": -1))
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, "-80", "-50", "80", "50")
		run "Immunizations/Util/Validation".verifyText "Dose 2", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure Dose 2 displays 8 weeks from dose 1 i.e.15 years + 11 months + 8 weeks from dose 1 within the timeline."
		run "Immunizations/Util/Validation".validationJiraComment "HMDEV-2045"
		Set alignment to ("Left", "Right")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set startDateHeader to "Immunizations/Util/Date".ageCalculator(dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 16)), false, false)
		set endDateHeader to "Immunizations/Util/Date".ageCalculator(dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 17)), false, false)
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		//Added Index 4 for startdate and enddate header because it's counting 15yrs as 16yrs
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleWithIndex("2", startDateHeader, "1", endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Util/Validation".verifyText "Dose 2", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		CaptureScreen(Name: "Step" & Global stepNumber & "-Dose 1 Charted Validation_P5")
		--------------------------------------------------------------------------------------------------------------- 
		
		Log "Util".stepNumber & "ACTION: Click on vaccine header and then click Dose 2 for Meningococcal vaccine."
		run "Immunizations/Forecaster-Forecast/Actions".clickVaccineName vaccineName
		click text: "2", searchrectangle: "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchrectangle()
		
		Log "VERIFICATION: Ensure in the right-hand pane, the following details are displayed at the bottom."
		Set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText "Dose 2", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: 1. Earliest: 8 weeks from Dose 1."
		set dose2MinimumDate to "Immunizations/Util/Date".adjustDate(dose1NewAdminDate, format, ("Week": 8))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField Minimum, dose2MinimumDate
		set dose2MinimumAge to "Immunizations/Util/Date".ageCalculator(dob, dose2MinimumDate, false, true)
		Set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle()
		Run "Immunizations/Util/Validation".verifyTextWithPattern dose2MinimumAge, "Immunizations/Util/Date".setPattern(dose2MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: 2. Recommended From: 8 weeks from Dose 1."
		set dose2EarliestRecommendedDate to "Immunizations/Util/Date".adjustDate(dose1NewAdminDate, format, ("Week": 8))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField EarliestRecommended, dose2EarliestRecommendedDate
		set dose2EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose2EarliestRecommendedDate, false, true)
		Run "Immunizations/Util/Validation".verifyTextWithPattern dose2EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose2EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(EarliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: 3. Recommended Until: 17 years + 4 weeks - 1 day from DOB."
		set dose3LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 17, "Week": 4, "Day": -1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField LatestRecommended, dose3LatestRecommendedDate
		set dose3LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose3LatestRecommendedDate, false, true)
		Run "Immunizations/Util/Validation".verifyTextWithPattern dose3LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose3LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(LatestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: 4. Latest: 19 years - 1 day from DOB."
		set dose2MaximumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year": 19, "Day": -1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField Maximum, dose2MaximumDate
		set dose2MaximumAge to "Immunizations/Util/Date".ageCalculator(dob, dose2MaximumDate, false, true)
		Run "Immunizations/Util/Validation".verifyTextWithPattern dose2MaximumAge, "Immunizations/Util/Date".setPattern(dose2MaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(Maximum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Ensure in the left-hand pane, Dose 2 displays with a status of 'Not Due Until' at the top and Recommended from Age (8 weeks from Dose 1) below it."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("2")
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & "Immunizations/Util/Date".adjustDate(dose1NewAdminDate, format, ("Week": 8)), rectangle
		CaptureScreen(Name: "Step" & Global stepNumber & "-Dose 2 Validation_P5")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "Close Patient 3's chart."
		run "Immunizations/Setup".closeApplication 
		---------------------------------------------------------------------------------------------------------------
		
		EndTestCase "VR/Meningococcal/HLM-VR-Immunizations-Meningococcal_Vaccine_Forecast_Cond_Skip"
		
	Catch
		LogError "Patient Workflow Steps Exception encountered: " && the exception.reason
		captureScreen "PWF_Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
	End Try
	
	#################################################################################
	# PATIENT CLEANUP
	Log "PATIENT CLEANUP: Open PmLaunch and Rename patient(s) from the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".renamePatientSearched newLastName
	run "Util".closeApplication 2
	---------------------------------------------------------------------------------------------------------------
	
Catch
	LogError "Exception encountered: " && the exception.reason
	captureScreen "Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
End Try
---------------------------------------------------------------------------------------------------------------

# SUT CLEANUP
run "Cleanup".zeroStateCloseAllApps
