--------------------------------------------------Helper Suite Information-------------------------------------------

#https://github.cerner.com/EggPlant/IPDev-Shared-Millennium
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-Immunizations
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-HealthMaintenanceTools
#https://github.cerner.com/EggPlant/IPDev-Shared-Utilities
------------------------------------------------RQM TEST CASE LINK--------------------------------------------------------

# https://jazz.cerner.com:9443/qm/web/console/IP#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestCase&id=62020

---------------------------------------Assigning Test Data to the Variables---------------------------------------
params domain 
set domain to "Immunizations/Util/setup".domainrun(domain)
Log "Test running in domain"&&domain
set format to "%b %d, %Y"
set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
set username to setup.username
set password to decodeText(setup.("password").trimAll, "HLM")
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set relationship to setup.relationship
set conversation to setup.conversation
set encounterOrg to setup.encounterOrg
set encounterType to setup.encounterType

set common to JSONValue(file resourcePath("Common.json"))
set menu to common.menu
set subMenu to common.subMenu
set noVaccineHistoryImage to common.noVaccineHistoryImage
set mPageChevronImage to common.mPageChevronImage
set doseInFocusImage to common.doseInFocusImage
set doubleDashImage to common.doubleDashImage

set fieldLabels to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("fieldLabels.json")),domain)
set minimum to fieldLabels.minimum
set earliestRecommended to fieldLabels.earliestRecommended
set latestRecommended to fieldLabels.latestRecommended
set maximum to fieldLabels.maximum

set textStrings to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("textStrings.json")),domain)
Set viewForecast to textStrings.viewForecast
Set notStarted to textStrings.notStarted
Set earliestRecommendedWithoutColon to textStrings.earliestRecommendedWithoutColon
Set notDueUntil to textStrings.notDueUntil

set testData to JSONValue(file resourcePath("VR/Rotavirus_3_Dose_Series/testData.json")).(value of domain)
set patientName to testData.Patient1.nameFullFormatted
set dob to formattedTime("%m/%d/%Y", value(testData.Patient1.dob)) 
set firstName to testData.Patient1.firstName
set lastName to testData.Patient1.lastName
set sex to testData.Patient1.sex
set newLastName to testData.Patient1.newLastName
set vaccineName to testData.vaccineName
set visLink1 to testData.visLink1


try
	------------------------------------------------------Patient setup---------------------------------------------------------
	Log "PATIENT CREATION: Open PmLaunch and Create patient(s) of 8 months - 1 day for the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, "%m/%d/%Y", dob, encounterType
	run "Util".closeApplication 2
	----------------------------------------------------------------------------------------------------------------------------------
	try
		------------------------------------------------------Test Steps---------------------------------------------------------
		BeginTestCase "VR/Rotavirus/HLM-VR-Immunizations-Rotavirus_3DoseSeries_Newborn"
		Log "Util".stepNumber &"ACTION: Open Powerchart.exe with User1, search for and open the chart for Patient1, and open the Immunizations Workflow component."
		run "Immunizations/setup".loginAndLoadcomponentViaMenu username, password, domain, patientName, menu, subMenu,  relationship
		
		Log "VERIFICATION: Verify the vaccine list is sorted by Status column by default in descending order by ensuring chevron is present in the status column."
		set rectangle to "Immunizations/WorkflowMPage/Table/Helpers".columnSearchRectangle("Status")
		run "Immunizations/Util/Validation".verifyImage mPageChevronImage, rectangle
		
		Log "VERIFICATION: Ensure Status, Administrations, Last action and Last action Date displays with '--'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, doubleDashImage
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, doubleDashImage
		run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionColumn vaccineName, doubleDashImage
		run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionDateColumn vaccineName, doubleDashImage
		
		Log "VERIFICATION: Ensure the Next recommended dose is displayed for <2 months from DOB> to <15 weeks - 1 day from DOB>."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName, "Immunizations/Util/Date".adjustDate(dob, format, ("month": 2)) && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("week": 15, "day": -1))
		capturescreen (Name:"Step" & Global stepNumber & "-MPage Review Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Rotavirus."
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName
		
		Log "VERIFICATION: Ensure the status and next recommended date '-- - <2 months from DOB> - <15 weeks - 1 day from DOB>' displays below the vaccine group name.Ensure 'No vaccine history to display' is shown in the middle of the detail pane."
		set rectangle to "Immunizations/WorkflowMPage/SidePanel/Helpers".sidePanelRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName, rectangle
		run "Immunizations/Util/Validation".verifyText "Immunizations/Util/Date".adjustDate(dob, format, ("month": 2)) && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("week": 15, "day": -1)), rectangle
		run "Immunizations/Util/Validation".verifyImage noVaccineHistoryImage, rectangle
		capturescreen (Name:"Step" & Global stepNumber & "-MPage Side Panel Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on the 'View Forecast' button."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		
		Log "VERIFICATION: In the CDC Schedule column, ensure Rotavirus displays with a status of 'Not Started' below it."
		set rectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName & return & notStarted, rectangle
		
		Log "VERIFICATION: Ensure dose 1 is forecasted from DOB + 2 months to DOB + 15 weeks - 1 day, that is from 2m to 3m 1w"
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 2))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("week": 15, "day": -1))
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleWithIndex(2, startDateHeader, 1, endDateHeader, "-50", "-30", "20", "100")
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText "Dose 1", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)				
		
		Log "VERIFICATION: Ensure dose 2 is forecasted from DOB + 4 months to DOB + 5 months + 4 weeks - 1 day, that is from 4m to 5m 3w"
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 4))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 5, "week": 4, "day": -1))
		set alignment to ("Left", "Right")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText "Dose 2", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure dose 3 is forecasted from DOB + 6 months to DOB + 7 months + 4 weeks - 1 day, that is from 6m to 7m 3w"
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 6))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 7, "week": 4, "day": -1))
		set alignment to ("Left", "Right")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText "Dose 3", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		capturescreen (Name:"Step" & Global stepNumber & "-Forecaster Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Rotavirus."
		run "Immunizations/Forecaster-Forecast/Actions".clickvaccineName vaccineName
		
		Log "VERIFICATION: Ensure Rotavirus displays with a blue background and a status of 'Not Started' in the left hand header."
		set leftPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewleftPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText vaccineName & return & notStarted, leftPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyImage doseInFocusImage, leftPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Ensure the right hand header displays with 'Not Started - Rotavirus' and 'Recommended from <2 months from DOB> - <15 weeks - 1 day from DOB>'."
		set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText notStarted && "-" && vaccineName & return & earliestRecommendedWithoutColon && "Immunizations/Util/Date".adjustDate(dob, "%m/%d/%y", ("month": 2)) && "-" && "Immunizations/Util/Date".adjustDate(dob, "%m/%d/%y", ("week": 15, "day": -1)), rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Ensure the VIS information displays in the body of the right hand side."
		set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle 
		run "Immunizations/Util/Validation".verifyText visLink1, rightPaneBodySearchRectangle
		capturescreen (Name:"Step" & Global stepNumber & "-Forecaster Expanded View Patient1") 
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Dose 1."
		Click text: "1", validCharacters:"*", SearchRectangle: "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchRectangle()
		
		Log "VERIFICATION: In the left hand pane, ensure dose 1 displays with a status of 'Not Due Until' and <2 months from DOB> below it."
		set leftPaneSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchRectangle("1")
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & "Immunizations/Util/Date".adjustDate(dob, format, ("month": 2)), leftPaneSearchRectangle
		
		Log "VERIFICATION: In the right hand pane, ensure 'Dose 1' in header"
		run "Immunizations/Util/Validation".verifyText "Dose 1", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: <6 weeks from DOB> (6w)"
		set dose1MinimumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Week": 6))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose1MinimumDate
		run "Immunizations/Util/Validation".validationJiraComment "IMMUN-1162"
		(*set dose1MinimumAge to "Immunizations/Util/Date".ageCalculator(dob, dose1MinimumDate, false, false)
		set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle()
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1MinimumAge, "Immunizations/Util/Date".setPattern(dose1MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle*)
		
		Log "VERIFICATION: Recommended From: <2 months from DOB> (2m)"
		set dose1EarliestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 2))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose1EarliestRecommendedDate
		set dose1EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose1EarliestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose1EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: <15 weeks - 1 day from DOB> (3m 1w)"
		set dose1LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("week": 15, "day": -1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose1LatestRecommendedDate
		set dose1LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose1LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose1LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Latest: <15 weeks - 1 day from DOB> (3m 1w) displays."
		set dose1MaximumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("week": 15, "day": -1)) 
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, dose1MaximumDate
		set dose1MaximumAge to "Immunizations/Util/Date".ageCalculator(dob, dose1MaximumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1MaximumAge, "Immunizations/Util/Date".setPattern(dose1MaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		capturescreen (Name:"Step" & Global stepNumber & "-Forecaster Expanded View Dose 1 Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Dose 2."
		Click text: "2", SearchRectangle: "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchRectangle()
		
		Log "VERIFICATION: In the left hand pane, ensure dose 2 displays with a status of 'Not Due Until' and <4 months from DOB> below it."
		set leftPaneSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchRectangle("2")
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & "Immunizations/Util/Date".adjustDate(dob, format, ("month": 4)), leftPaneSearchRectangle
		
		Log "VERIFICATION: In the right hand pane, ensure 'Dose 2' in header"
		run "Immunizations/Util/Validation".validationJiraComment "IMMUN-1162"
		run "Immunizations/Util/Validation".verifyText "Dose 2", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: <10 weeks from DOB> (2m 1w)"
		set dose2MinimumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Week": 10))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose2MinimumDate
		set dose2MinimumAge to "Immunizations/Util/Date".ageCalculator(dob, dose2MinimumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2MinimumAge, "Immunizations/Util/Date".setPattern(dose2MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommened From: <4 months from DOB> (4m)"
		set dose2EarliestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 4))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose2EarliestRecommendedDate
		set dose2EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose2EarliestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose2EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: <5 months + 4 weeks - 1 day from DOB> (5m 3w)"
		set dose2LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 5, "week": 4, "day": -1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose2LatestRecommendedDate
		set dose2LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose2LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose2LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Latest: <8 months from DOB> (8m) displays."
		set doseMaximumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 8))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, doseMaximumDate
		set doseMaximumAge to "Immunizations/Util/Date".ageCalculator(dob, doseMaximumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern doseMaximumAge, "Immunizations/Util/Date".setPattern(doseMaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		capturescreen (Name:"Step" & Global stepNumber & "-Forecaster Expanded View Dose 2 Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on dose 3."
		Click text: "3", SearchRectangle: "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchRectangle()
		
		Log "VERIFICATION: In the left hand pane, ensure dose 3 displays with a status of 'Not Due Until' and <6 months from DOB> below it."
		set leftPaneSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchRectangle("3")
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & "Immunizations/Util/Date".adjustDate(dob, format, ("month": 6)), leftPaneSearchRectangle
		
		Log "VERIFICATION: In the right hand pane, ensure 'Dose 3' in header"
		run "Immunizations/Util/Validation".verifyText "Dose 3", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: <14 weeks from DOB> (3m)"
		set dose3MinimumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Week": 14))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose3MinimumDate
		set dose3MinimumAge to "Immunizations/Util/Date".ageCalculator(dob, dose3MinimumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3MinimumAge, "Immunizations/Util/Date".setPattern(dose3MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommened From: <6 months from DOB> (6m)"
		set dose3EarliestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 6))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose3EarliestRecommendedDate
		set dose3EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose3EarliestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose3EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: <7 months + 4 weeks - 1 day from DOB> (7m 3w)"
		set dose3LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 7, "week": 4, "day": -1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose3LatestRecommendedDate
		set dose3LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose3LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose3LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Latest: <8 months from DOB> (8m) displays."
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, doseMaximumDate
		run "Immunizations/Util/Validation".verifyTextWithPattern doseMaximumAge, "Immunizations/Util/Date".setPattern(doseMaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		capturescreen (Name:"Step" & Global stepNumber & "-Forecaster Expanded View Dose 3 Patient1")
		---------------------------------------------------------------------------------------------------------------
		Log "Util".stepNumber &"ACTION: Close Application."
		run "Immunizations/setup".closeApplication 
		
		EndTestCase "VR/Rotavirus/HLM-VR-Immunizations-Rotavirus_3DoseSeries_Newborn"
		---------------------------------------------------------------------------------------------------------------
	catch
		LogError "Patient Workflow Steps Exception encountered: " && the exception.reason
		captureScreen "PWF_Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
	end try
	------------------------------------------------------Patient Cleanup----------------------------------------------
	Log "PATIENT CLEANUP: Open PmLaunch and Rename patient(s) from the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".renamePatientSearched newLastName
	run "Util".closeApplication 2
	---------------------------------------------------------------------------------------------------------------
catch
	LogError "Exception encountered" && the exception.reason
	captureScreen"Exception"
End Try
---------------------------------------------------------------------------------------------------------------

# SUT CLEANUP
run "Cleanup".ZeroStateCloseAllApps	