--------------------------------------------------Helper Suite Information-------------------------------------------

#https://github.cerner.com/EggPlant/IPDev-Shared-Millennium
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-Immunizations
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-HealthMaintenanceTools
#https://github.cerner.com/EggPlant/IPDev-Shared-Utilities
------------------------------------------------RQM TEST CASE LINK--------------------------------------------------------

# https://jazz.cerner.com:9443/qm/web/console/IP#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestCase&id=123817

---------------------------------------Assigning Test Data to the Variables---------------------------------------
params domain 
set domain to "Immunizations/Util/setup".domainrun(domain)
Log "Test running in domain"&&domain
set format to "%b %d, %Y"
set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
set username to setup.username
set password to decodeText(setup.("password").trimAll, "HLM")
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set relationship to setup.relationship
set conversation to setup.conversation
set encounterOrg to setup.encounterOrg
set encounterType to setup.encounterType

set common to JSONValue(file resourcePath("Common.json"))
set menu to common.menu
set subMenu to common.subMenu
set viewPoint to common.viewPoint
set didNotCountImage to common.didNotCountImage
set doubleDashImage to common.doubleDashImage
set rotavirusVaccineStrikeThroughImg to common.rotavirusVaccineStrikeThroughImg

set textStrings to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("textStrings.json")),domain)
Set viewForecast to textStrings.viewForecast
Set agedOut to textStrings.agedOut
set administeredDidNotCount to textStrings.administeredDidNotCount

set testData to JSONValue(file resourcePath("VR/Rotavirus_3_Dose_Series/testData.json")).(value of domain)
set patientName to testData.patient5.nameFullFormatted
set dob to formattedTime("%m/%d/%Y", value(testData.Patient5.dob)) 
set firstName to testData.Patient5.firstName
set lastName to testData.Patient5.lastName
set sex to testData.Patient5.sex
set newLastName to testData.Patient5.newLastName
set vaccineName to testData.vaccineName
set source to testData.source
set product to testData.product
set dateFormat to testData.dateFormat


try
	------------------------------------------------------Patient setup---------------------------------------------------------
	Log "PATIENT CREATION: Open PmLaunch and Create patient(s) of 8 months - 1 day for the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, "%m/%d/%Y", dob, encounterType
	run "Util".closeApplication 2
	----------------------------------------------------------------------------------------------------------------------------------
	try
		------------------------------------------------------Test Steps---------------------------------------------------------
		BeginTestCase "VR/Rotavirus/HLM-VR-Immunizations-Rotavirus_3DoseSeries_Aged_Out"
		Log "Util".stepNumber &"ACTION: Open Patient 5's chart, navigate to the immunization component and review the MPage."
		Run "Immunizations/setup".loginAndLoadcomponentViaMenu username, password, domain, patientName, menu, subMenu,  relationship
		
		Log "VERIFICATION: Ensure Rotavirus vaccine displays.with a status of Aged Out in historical section. Ensure the Next recommended dose is displayed as '--'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, agedOut
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName, doubleDashImage
		capturescreen (Name: "Step" & Global stepNumber & "- MPage Review Patient5")
		--------------------------------------------------------------------------------------------------------------- 		
		Log "Util".stepNumber &"ACTION: Click on Immunization Forecaster."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangleImage(rotavirusVaccineStrikeThroughImg)
		
		Log "VERIFICATION: Ensure is Rotavirus displayed under CDC schedule column with a strikethrough line on the Vaccine group name with Aged Out below it. Ensure no doses are displayed within the timeline."
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyImage rotavirusVaccineStrikeThroughImg, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle), 
		run "Immunizations/Util/Validation".verifyText agedOut, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure no doses are displayed within the timeline for Rotavirus."
		set ScrollBarRightArrow to imageLocation("Immunizations/Forecaster-Forecast/Search/Icon_ScrollBarRightArrow")
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyTextNotVisible "Dose", "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangleImage(rotavirusVaccineStrikeThroughImg)
		CaptureScreen(Name: "Step" & Global stepNumber & "-Forecaster today til 14yrs Patient5")
		
		set startDateHeader to "Immunizations/Util/Date".todaysDate(format)+1 day
		set endDateHeader to "Immunizations/Util/Date".todaysDate(format)+1 day
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader ,"-20", "-30", "1200","100")
		run "Immunizations/Util/Validation".verifyTextNotVisible "Dose", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		CaptureScreen(Name: "Step" & Global stepNumber & "-Forecaster 14yrs to 23yrs Patient5")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Chart a dose at 15 weeks from DOB using product RotaTeq and review the forecaster."
		set dose1AdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("week": 15))
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName, dateFormat, dose1AdminDate, source, product, "Submit"	
		
		Log "VERIFICATION: Ensure the dose 1 displays in the forecaster with the product name and date of administration."
		set startDateHeader to dose1AdminDate
		set endDateHeader to dose1AdminDate
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, "-120", "-30", "60", "100")
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText product & return & "Dose 1" && "-" && dose1AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		CaptureScreen(Name: "Step" & Global stepNumber & "-Dose1 Charted Patient5")
		---------------------------------------------------------------------------------------------------------------
		Log "Util".stepNumber &"ACTION: Chart a dose at 8 months from DOB using product RoaTeq and review the forecaster."
		set dose2AdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 8))
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName, dateFormat, dose2AdminDate, source, product, "Submit"	
		
		Log "VERIFICATION: Ensure the dose 2 displays in the forecaster with the product name and date of administration."
		set startDateHeader to dose2AdminDate
		set endDateHeader to dose2AdminDate
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangleImage(rotavirusVaccineStrikeThroughImg)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, "-120", "-30", "60", "100")
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText product & return & "Dose 2" && "-" && dose2AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		CaptureScreen(Name: "Step" & Global stepNumber & "-Dose2 Charted Patient5")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Navigate back to the MPage, open the side panel and modify dose 2 so that the administration date is today"
		run "Immunizations/Common/actions".clickMPagesView viewPoint
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName
		set dose2NewAdminDate to "Immunizations/Util/Date".todaysDate(format)
		run "Immunizations/WorkFlowMPage/SidePanel/Task".modifyAdminDate dose2AdminDate, "1", dateFormat, dose2NewAdminDate
		
		Log "VERIFICATION: Ensure Rotavirus moves to the historical section with a status of 'Aged Out', administrations of 2 with the did not count icon, next recommended of '--', and last action of administered - Did Not Count."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyvaccineNameHistorySection vaccineName
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, agedOut
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, "2"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, "Did Not Count"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName, doubleDashImage
		run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionColumn vaccineName, administeredDidNotCount
		CaptureScreen(Name: "Step" & Global stepNumber & "-Dose2 modified Did Not count Patient5")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Navigate to the forecaster and click on the the list view."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		run "Immunizations/Forecaster-Common/Actions".clickFlipViews
		
		Log"VERIFICATION: Ensure Rotavirus displays with a strikethrough and a status of 'Aged Out' in the vaccine column."
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangleImage(rotavirusVaccineStrikeThroughImg)
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText agedOut, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Action column displays Dose 1 with product or or default event set name on top and administrations date with age in parenthesis below it" 
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchRectangle("1")
		run "Immunizations/Util/Validation".verifyText product & return & dose1AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		set dose1AdminAge to "Immunizations/Util/Date".ageCalculator(dob, dose1AdminDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1AdminAge, "Immunizations/Util/Date".setPattern(dose1AdminAge), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Action column displays Dose 2 with product or default event set name and did not count icon on top and administrations date with age in parenthesis below it" 
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchRectangle("2")
		run "Immunizations/Util/Validation".verifyImage didNotCountImage, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText product & return & dose2NewAdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		set dose2NewAdminAge to "Immunizations/Util/Date".ageCalculator(dob, dose2NewAdminDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2NewAdminAge, "Immunizations/Util/Date".setPattern(dose2NewAdminAge), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		capturescreen (Name: "Step" & Global stepNumber & "- List view patient5")
		--------------------------------------------------------------------------------------------------------------
		Log "Util".stepNumber &"ACTION: Close Application."
		run "Immunizations/setup".closeApplication 
		
		EndTestCase "VR/Rotavirus/HLM-VR-Immunizations-Rotavirus_3DoseSeries_Aged_Out"
		---------------------------------------------------------------------------------------------------------------
	catch
		LogError "Patient Workflow Steps Exception encountered: " && the exception.reason
		captureScreen "PWF_Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
	end try
	------------------------------------------------------Patient Cleanup----------------------------------------------
	Log "PATIENT CLEANUP: Open PmLaunch and Rename patient(s) from the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".renamePatientSearched newLastName
	run "Util".closeApplication 2
	---------------------------------------------------------------------------------------------------------------
catch
	LogError "Exception encountered" && the exception.reason
	captureScreen"Exception"
End Try
---------------------------------------------------------------------------------------------------------------

# SUT CLEANUP
run "Cleanup".ZeroStateCloseAllApps	