--------------------------------------------------Helper Suite Information-------------------------------------------

#https://github.cerner.com/EggPlant/IPDev-Shared-Millennium
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-Immunizations
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-HealthMaintenanceTools
#https://github.cerner.com/EggPlant/IPDev-Shared-Utilities

------------------------------------------------RQM TEST CASE LINK--------------------------------------------------------

#https://jazz.cerner.com:9443/qm/web/console/IP#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestCase&id=123815

---------------------------------------Assigning Test Data to the Variables---------------------------------------
params domain 
set domain to "Immunizations/Util/setup".domainrun(domain)
Log "Test running in domain" && domain
set format to "%b %d, %Y"
set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
set username to setup.username
set password to decodeText(setup.("password").trimAll, "HLM")
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set relationship to setup.relationship
set conversation to setup.conversation
set encounterOrg to setup.encounterOrg
set encounterType to setup.encounterType

set common to JSONValue(file resourcePath("Common.json"))
set menu to common.menu
set subMenu to common.subMenu
set viewPoint to common.viewPoint
set doubleDashImage to common.doubleDashImage

set fieldLabels to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("fieldLabels.json")),domain)
set minimum to fieldLabels.minimum
set earliestRecommended to fieldLabels.earliestRecommended
set latestRecommended to fieldLabels.latestRecommended
set maximum to fieldLabels.maximum
set performedDateField to fieldLabels.performedDateField
set userField to fieldLabels.userField
set sourceField to fieldLabels.sourceField
set documentedDateField to fieldLabels.documentedDateField
set productNameField to fieldLabels.productNameField
set documentedByField to fieldLabels.documentedByField
set mpageSourceField to fieldLabels.mpageSourceField
set productField to fieldLabels.productField

set textStrings to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("textStrings.json")),domain)
Set viewForecast to textStrings.viewForecast
Set agedOut to textStrings.agedOut
Set lastAdmin to textStrings.lastAdmin
Set administeredOn to textStrings.administeredOn
Set overdue to textStrings.overdue
Set administeredDidNotCount to textStrings.administeredDidNotCount
Set complete to textStrings.complete
Set printRecord to textStrings.printRecord

set testData to JSONValue(file resourcePath("VR/Rotavirus_3_Dose_Series/testData.json")).(value of domain)
set patientName to testData.Patient4.nameFullFormatted
set dob to formattedTime("%m/%d/%Y", value(testData.Patient4.dob)) 
set user to testData.user
set firstName to testData.Patient4.firstName
set lastName to testData.Patient4.lastName
set sex to testData.Patient4.sex
set newLastName to testData.Patient4.newLastName
set vaccineName to testData.vaccineName
set source to testData.source
set product to testData.product
set product2 to testData.product2
set dateFormat to testData.dateFormat
set waitFor to testData.waitFor


try
	------------------------------------------------------Patient setup---------------------------------------------------------
	Log "PATIENT CREATION: Open PmLaunch and Create patient(s) of 8 months - 1 day for the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, "%m/%d/%Y", dob, encounterType
	run "Util".closeApplication 2
	----------------------------------------------------------------------------------------------------------------------------------
	try
		------------------------------------------------------Test Steps---------------------------------------------------------
		BeginTestCase "VR/Rotavirus/HLM-VR-Immunizations-Rotavirus_3DoseSeries_Overdue"
		Log "Util".stepNumber & "ACTION: Open Patient 4's chart, navigate to the immunization component and review the MPage."
		run "Immunizations/setup".loginAndLoadcomponentViaMenu username, password, domain, patientName, menu, subMenu,  relationship
		
		Log "VERIFICATION: Verify is Rotavirus within the history section with Status 'Aged Out' and Next Dose Recommended column displays with '--'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, agedOut
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName, doubleDashImage
		capturescreen (Name:"Step" & Global stepNumber & "- MPage Review Patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Click on Immunization Forecaster and chart Dose 1 at 15 weeks from DOB using product Rotarix."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		set dose1AdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("week": 15))
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName, dateFormat, dose1AdminDate, source, product2, "Submit"	
		
		Log "VERIFICATION: Under the CDC Schedule column, ensure Rotavirus displays with 'Last Admin: <DOB + 15 weeks > (3m 1w)'."
		set rectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName, rectangle
		run "Immunizations/Util/Validation".verifyText lastAdmin && dose1AdminDate, rectangle
		set dose1AdminAge to "Immunizations/Util/Date".ageCalculator(dob, dose1AdminDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1AdminAge, "Immunizations/Util/Date".setPattern(dose1AdminAge), rectangle
		
		Log "VERIFICATION: Ensure dose 1 is charted with product or default event set name along with the date of administration in the cell."
		set startDateHeader to dose1AdminDate
		set endDateHeader to dose1AdminDate
		set alignment to ("Center", "Center")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText product2 & return & "Dose 1" && "-" && dose1AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure dose 2 is forecasted for today."
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyText "Dose 2", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure no more doses are forecasted."
		set ScrollBarRightArrow to imageLocation("Immunizations/Forecaster-Forecast/Search/Icon_ScrollBarRightArrow")
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle("Immunizations/Util/Date".todaysDate(format)+1 day, "Immunizations/Util/Date".ageCalculator(dob, "Immunizations/Util/Date".adjustDate(dob, format, ("year": 7)), false, false), "-110", "-30", "50", "100")
		run "Immunizations/Util/Validation".verifyTextNotVisible "Dose", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		CaptureScreen(Name:"Step" & Global stepNumber & "-Dose1 charted patient4")
		
		//Scrolling through the forecaster to validate no doses displaying (Quicker than handler)
		Repeat 5 times
			Click ScrollBarRightArrow
		End repeat
		
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle("Immunizations/Util/Date".ageCalculator(dob, "Immunizations/Util/Date".adjustDate(dob, format, ("year": 7)), false, false), "Immunizations/Util/Date".ageCalculator(dob, "Immunizations/Util/Date".adjustDate(dob, format, ("year": 23, "month": 1)), false, false), "-110", "-30", "50", "100")
		run "Immunizations/Util/Validation".verifyTextNotVisible "Dose", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		CaptureScreen(Name:"Step" & Global stepNumber & "-Forecaster 13yrs to 23yrs patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Click on Dose 1."
		click text: "Today", searchRectangle: "Immunizations/Common/Helpers".tabListSearchRectangle
		set startDateHeader to dose1AdminDate
		set endDateHeader to dose1AdminDate
		set alignment to ("Center", "Center")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		Click text: "Dose 1", searchRectangle: "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchrectangle)
		
		Log "VERIFICATION: Ensure only 2 doses are forecasted"
		run "Immunizations/Util/Validation".verifyTextNotVisible "3", "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchRectangle()
		
		Log "VERIFICATION: In the left hand pane, ensure dose 1 is displayed with Rotarix along with <DOB + 15 weeks> (3m 1w)."
		set leftPaneSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchRectangle("1")
		run "Immunizations/Util/Validation".verifyText product2 & return & dose1AdminDate, leftPaneSearchRectangle
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1AdminAge, "Immunizations/Util/Date".setPattern(dose1AdminAge), leftPaneSearchRectangle
		
		Log "VERIFICATION: In the right hand pane header, ensure 'Administered On <DOB + 15 weeks> - Rotarix' displays."
		set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText administeredOn && dose1AdminDate && "-" && product2, rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: In the body of the right hand pane, ensure the proper administration details are populated and displayed."
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField performedDateField, dose1AdminDate
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField userField, user
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField sourceField, source
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField documentedDateField, "Immunizations/Util/Date".todaysDate(format)
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField productNameField, product2
		capturescreen (Name:"Step" & Global stepNumber & "- Dose1 Charted Expanded View Patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Chart the second dose at 4 weeks - 4 days from dose 1 with product RotaTeq."
		Click text: "Print", searchRectangle: "Immunizations/Common/Helpers".tabListSearchRectangle
		set dose2AdminDate to "Immunizations/Util/Date".adjustDate(dose1AdminDate, format, ("week": 4, "day": -4))
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName, dateFormat, dose2AdminDate, source, product, "Submit"	
		
		Log "VERIFICATION: Under the CDC Schedule column, ensure Rotavirus displays with 'Last Admin: <Dose 1 + 4 weeks - 4 days> (4m)'."
		set rectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName, rectangle
		run "Immunizations/Util/Validation".verifyText lastAdmin && dose2AdminDate, rectangle
		set dose2AdminAge to "Immunizations/Util/Date".ageCalculator(dob, dose2AdminDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2AdminAge, "Immunizations/Util/Date".setPattern(dose2AdminAge), rectangle
		
		Log "VERIFICATION: Ensure dose 2 is charted with product or default event set name along with the date of administration in the cell."
		set startDateHeader to dose2AdminDate
		set endDateHeader to dose2AdminDate
		set alignment to ("Center", "Center")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText product & return & "Dose 2" && "-" && dose2AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure dose 3 is now forecasted for today."
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyText "Dose 3", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		capturescreen (Name:"Step" & Global stepNumber & "- Dose2 Charted Patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Click on Dose 2."
		set startDateHeader to dose2AdminDate
		set endDateHeader to dose2AdminDate
		set alignment to ("Center", "Center")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		Click text: "Dose 2", searchRectangle: "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchrectangle)
		
		Log "VERIFICATION: In the left hand pane, ensure dose 2 is displayed with RotaTeq along with <4 weeks - 4 days from dose 1> (4m)."
		set leftPaneSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchRectangle("2")
		run "Immunizations/Util/Validation".verifyText product & return & dose2AdminDate, leftPaneSearchRectangle
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2AdminAge, "Immunizations/Util/Date".setPattern(dose2AdminAge), leftPaneSearchRectangle
		
		Log "VERIFICATION: In the right hand pane header, ensure 'Administered On <4 weeks - 4 days from dose 1> - RotaTeq' displays."
		run "Immunizations/Util/Validation".verifyText administeredOn && dose2AdminDate && "-" && product, rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: In the body of the right hand pane, ensure the proper administration details are populated and displayed."
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField performedDateField, dose2AdminDate
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField userField, user
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField sourceField, source
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField documentedDateField, "Immunizations/Util/Date".todaysDate(format)
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField productNameField, product
		capturescreen (Name:"Step" & Global stepNumber & "- Dose2 Charted Expanded View Patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Click on dose 3."
		Click text: "3", searchRectangle: "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchRectangle()
		
		Log "VERIFICATION: In the left hand pane, ensure dose 3 displays with a status of 'Overdue' and <7 months + 4 weeks - 1 day from DOB> below it."
		set leftPaneSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchRectangle("3")
		run "Immunizations/Util/Validation".verifyText overdue & return & "Immunizations/Util/Date".adjustDate(dob, format, ("month": 7, "week": 4, "day": -1)), leftPaneSearchRectangle
		
		Log "VERIFICATION: Ensure the numbering for the doses in the expanded view is sorted correctly"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewSorting
		
		Log "VERIFICATION: In the right hand pane, ensure 'Dose 3' in header"
		set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText "Dose 3", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: <4 weeks from dose 2> (5m)"
		set dose3MinimumDate to "Immunizations/Util/Date".adjustDate(dose2AdminDate, format, ("week": 4))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose3MinimumDate
		set dose3MinimumAge to "Immunizations/Util/Date".ageCalculator(dob, dose3MinimumDate, false, false)
		Set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle()
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3MinimumAge, "Immunizations/Util/Date".setPattern(dose3MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommened From: <6 months from DOB> (6m)"
		set dose3EarliestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 6))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose3EarliestRecommendedDate
		set dose3EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose3EarliestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose3EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: <7 months + 4 weeks - 1 day from DOB> (7m 3w)"
		set dose3LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 7, "week": 4, "day": -1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose3LatestRecommendedDate
		set dose3LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose3LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose3LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: , Latest: <8 months from DOB> (8m) displays."
		set dose3MaximumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("month": 8))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, dose3MaximumDate
		set dose3MaximumAge to "Immunizations/Util/Date".ageCalculator(dob, dose3MaximumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3MaximumAge, "Immunizations/Util/Date".setPattern(dose3MaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		capturescreen (Name:"Step" & Global stepNumber & "- Expanded View Dose 3 Patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Click outside the expanded view and navigate back to the MPage"
		Click text: "Print", searchRectangle: "Immunizations/Common/Helpers".tabListSearchRectangle
		run "Immunizations/Common/actions".clickMPagesView viewPoint
		
		Log "VERIFICATION: Ensure Rotavirus displays with a status of 'Overdue' and the next recommended dose is for today."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, overdue
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, "2"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName, "Today"
		capturescreen (Name:"Step" & Global stepNumber & "- Workflow MPage status overdue patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Chart dose 3 at 4 weeks - 5 days from dose 2 using product RotaTeq."
		set dose3AdminDate to "Immunizations/Util/Date".adjustDate(dose2AdminDate, format, ("week": 4, "day": -5))
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName, dateFormat, dose3AdminDate, source, product, "Submit"	
		
		Log "VERIFICATION: Ensure administrations displays with '3' along with the did not count icon.Ensure the last action displays as 'Administered - Did Not Count'.Ensure the status remains as overdue"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, "3"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, "Did Not Count"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionColumn vaccineName, administeredDidNotCount
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, overdue
		capturescreen (Name:"Step" & Global stepNumber & "- Workflow MPage dose 3 patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Open the side panel and modify the third dose such that it is 4 weeks - 4 days from dose 2."
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName
		set dose3NewAdminDate to "Immunizations/Util/Date".adjustDate(dose2AdminDate, format, ("week": 4, "day": -4))
		run "Immunizations/WorkFlowMPage/SidePanel/Task".modifyAdminDate dose3AdminDate, "1", dateFormat, dose3NewAdminDate
		
		Log "VERIFICATION: Ensure rotavirus moves to the historical section with a status of complete, administrations of 3, next recommended of '--', last action of administered, and last action date <4 weeks - 4 days from dose 2> (5m)."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameHistorySection vaccineName
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, complete
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName, "--"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionColumn vaccineName, "Administered"
		set dose3NewAdminAge to "Immunizations/Util/Date".ageCalculator(dob, dose3NewAdminDate, false, false)
		run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionDateColumn vaccineName, dose3NewAdminDate, dose3NewAdminAge
		capturescreen (Name:"Step" & Global stepNumber & "- Workflow MPage dose 3 modified patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Click on Rotavirus."
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName
		
		Log "VERIFICATION: Ensure Rotavirus displays with a status of complete in the header."
		set sidePanelRectangle to "Immunizations/WorkflowMPage/SidePanel/Helpers".sidePanelRectangle
		run "Immunizations/Util/Validation".verifyText vaccineName & return & complete, sidePanelRectangle
		
		Log "VERIFICATION:In the body, ensure dose 3 is displayed <4 weeks - 4 days from dose 2> (5m) along with the Documented by, source, and product fields populated."
		run "Immunizations/WorkflowMPage/SidePanel/Validations".lastActionWithIndex "1", documentedByField, sidePanelRectangle, dose3NewAdminDate
		run "Immunizations/WorkflowMPage/SidePanel/Validations".lastActionWithIndex "1", documentedByField, sidePanelRectangle, "-" && "Administered"
		set rectangle to (item 1 of everyImageLocation(text: documentedByField, searchRectangle: (sidePanelRectangle))+(-50, -50), item 1 of everyImageLocation(text: documentedByField, searchRectangle: (sidePanelRectangle))+(350, 0))
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3NewAdminAge, "Immunizations/Util/Date".setPattern(dose3NewAdminAge), rectangle	
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "1", documentedByField, sidePanelRectangle, user
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "1", mpageSourceField, sidePanelRectangle, source
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "1", productField, sidePanelRectangle, product
		capturescreen (Name:"Step" & Global stepNumber & "- Workflow MPage side panel patient3")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Click on the View Forecast link and navigate to the list view."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		run "Immunizations/Forecaster-Common/Actions".clickFlipViews
		
		Log "VERIFICATION: Ensure under the vaccine column, Rotavirus displays with a status of 'Complete'.Ensure that doses 1 and 2 are displayed under the action columns with the vaccine name, date of administration and age in parenthesis."
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText complete, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Action column displays Dose 1 with product or or default event set name on top and administrations date with age in parenthesis below it" 
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchrectangle("1")
		run "Immunizations/Util/Validation".verifyText "1" && product2 & return & dose1AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1AdminAge, "Immunizations/Util/Date".setPattern(dose1AdminAge), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Action column displays Dose 2 with product or or default event set name on top and administrations date with age in parenthesis below it" 
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchrectangle("2")
		run "Immunizations/Util/Validation".verifyText "2" && product & return & dose2AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2AdminAge, "Immunizations/Util/Date".setPattern(dose2AdminAge), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Action column displays Dose 3 with product or or default event set name on top and administrations date with age in parenthesis below it" 
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchrectangle("3")
		run "Immunizations/Util/Validation".verifyText "3" && product & return & dose3NewAdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3NewAdminAge, "Immunizations/Util/Date".setPattern(dose3NewAdminAge), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle, columnSearchRectangle)
		capturescreen (Name:"Step" & Global stepNumber & "- list view patient4")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "ACTION: Click outside expanded view and click on 'Print Record'."
		run "Immunizations/Common/Print/Actions".clickPrintRecord(printRecord)
		
		Log "VERIFICATION: Rotavirus is displayed within the Vaccine column"
		run "Immunizations/Util/Validation".verifyText vaccineName, "Immunizations/Common/Print/Helpers".vaccineColumnSearchRectangle()
		
		Log "VERIFICATION: The administration for 15 weeks displays in the row for Rotavirus in the Date Given column."
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1AdminDate, "Immunizations/Util/Date".setPattern(dose1AdminDate), "Immunizations/Common/Print/Helpers".dateGivenSearchRectangle("true", 1, 1)
		
		Log "VERIFICATION: The administration for 4 weeks - 4 from dose 1 displays in the row for Rotavirus in the Date Given column."
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2AdminDate, "Immunizations/Util/Date".setPattern(dose2AdminDate), "Immunizations/Common/Print/Helpers".dateGivenSearchRectangle("true", 1, 2)
		
		Log "VERIFICATION: The administration for 4 weeks - 4 from dose 2 displays in the row for Rotavirus in the Date Given column."
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3NewAdminDate, "Immunizations/Util/Date".setPattern(dose3NewAdminDate), "Immunizations/Common/Print/Helpers".dateGivenSearchRectangle("true", 1, 3)
		
		Log "VERIFICATION: The product administered at 15 weeks from DOB is displayed in the Product column for Rotavirus"
		run "Immunizations/Util/Validation".verifyText product2, "Immunizations/Common/Print/Helpers".productSearchRectangle("true", 1, 1)
		
		Log "VERIFICATION: The product administered at 4 weeks - 4 days from dose 1 is displayed in the Product column for Rotavirus"
		run "Immunizations/Util/Validation".verifyText product, "Immunizations/Common/Print/Helpers".productSearchRectangle("true", 1, 2)
		
		Log "VERIFICATION: The product administered at 4 weeks - 4 days from dose 2 is displayed in the Product column for Rotavirus"
		run "Immunizations/Util/Validation".verifyText product, "Immunizations/Common/Print/Helpers".productSearchRectangle("true", 1, 3)
		CaptureScreen(Name:"Step" & Global stepNumber & "- Print Report Patient3")
		---------------------------------------------------------------------------------------------------------------
		Log "Util".stepNumber &"ACTION: Close Application."
		run "Immunizations/setup".closeApplication 
		
		EndTestCase "VR/Rotavirus/HLM-VR-Immunizations-Rotavirus_3DoseSeries_Overdue"
		---------------------------------------------------------------------------------------------------------------
	catch
		LogError "Patient Workflow Steps Exception encountered: " && the exception.reason
		captureScreen "PWF_Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
	end try
	------------------------------------------------------Patient Cleanup----------------------------------------------
	Log "PATIENT CLEANUP: Open PmLaunch and Rename patient(s) from the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".renamePatientSearched newLastName
	run "Util".closeApplication 2
	---------------------------------------------------------------------------------------------------------------
catch
	LogError "Exception encountered" && the exception.reason
	captureScreen"Exception"
End Try
---------------------------------------------------------------------------------------------------------------

# SUT CLEANUP
run "Cleanup".ZeroStateCloseAllApps	