-------------------------------------------------Helper Suite Information-------------------------------------------

#https://github.cerner.com/EggPlant/IPDev-Shared-Millennium
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-Immunizations
#https://github.cerner.com/EggPlant/IPDev-Millennium-Shared-HealthMaintenanceTools
#https://github.cerner.com/EggPlant/IPDev-Shared-Utilities
------------------------------------------------------------------------------------------------------------------------------

#RQM TEST CASE LINK: https://jazz.cerner.com:9443/qm/web/console/IP#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestCase&id=122836

params domain
log "Test running in domain"&&domain 

set domain to "Immunizations/Util/Setup".domainRun(domain)
set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
log "commonData:" && setup
set nonDbaUserName to setup.nonDbaUserName
set password to decodeText(setup.("password").trimAll, "HLM")
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set relationship to setup.relationship
set conversation to setup.conversation
set encounterOrg to setup.EncounterOrg
set  encounterType to setup.EncounterType

set common to JSONValue(file resourcePath("common.json"))
set menu to common.menu
set subMenu to common.subMenu
set viewpoint to common.viewpoint
Set didNotCountImage to common.didNotCountImage
Set unchartIconImage to common.unchartIconImage
set doubleDashImage to common.doubleDashImage

set fieldLabels to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("fieldLabels.json")),domain)
set minimum to fieldLabels.minimum
set earliestRecommended to fieldLabels.earliestRecommended
set latestRecommended to fieldLabels.latestRecommended
set maximum to fieldLabels.maximum
set performedDateField to fieldLabels.performedDateField
set userField to fieldLabels.userField
set sourceField to fieldLabels.sourceField
set documentedDateField to fieldLabels.documentedDateField
set productNameField to fieldLabels.productNameField

set textStrings to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("textStrings.json")),domain)
set overdue to textStrings.overdue
set notDueUntil to textStrings.notDueUntil
set viewForecast to textStrings.viewForecast
set complete to textStrings.complete
set notStarted to textStrings.notStarted
set administered to textStrings.administered
set forecastSuspended to textStrings.forecastSuspended
set lastAdmin to textStrings.lastAdmin
set due to textStrings.due

set testData to JSONValue(file resourcePath("VR/Varicella_Vaccine_Forecast/TestData.json")).(value of domain)
set lastName to testData.Patient_Overdue.lastName
set firstName to testData.Patient_Overdue.firstName
set patientName to testData.Patient_Overdue.nameFullFormatted
set newLastName to testData.Patient_Overdue.newLastName
set sex to  testData.Patient_Overdue.sex
set dob to formattedTime("%m/%d/%Y", value(testData.Patient_Overdue.dob))
set vaccineName1 to testData.vaccineName1
set vaccineName2 to testData.vaccineName2
set vaccineName3 to testData.vaccineName3
set product1 to testData.product1
set product2 to testData.product2
set product3 to testData.product3
set dateFormat to testData.dateFormat
set eventSet to testData.eventSet
set source to testData.source
set user to testData.Patient_Overdue.user
set unchartedReason to testData.unchartedReason
set format to "%b %d, %Y"

Try
	#PATIENT CREATION
	log "Create patient1 (4 years old) for the test"
	run "Immunizations/PatientCreation".openPMLaunch nonDbaUserName, password, domain
	run "Immunizations/PatientCreation".openConversation conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, "%m/%d/%Y", dob, encounterType
	run "Util".closeApplication 2
	
	try
		BeginTestCase "HLM-VR-Immunizations-Varicella_Overdue"
		
		log "Util".stepNumber & "ACTION: Open Patient's chart to Immunization Workflow MPage and navigate to Immunization section."
		run "Immunizations/setup".LoginAndLoadComponentViaMenu nonDbaUserName, Password, Domain, patientName, Menu, SubMenu, relationship
		
		Log "VERIFICATION: Ensure the Immunization Workflow MPage displays."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameColumn vaccineName1
		
		Log "VERIFICATION: Ensure Varicella is displayed in Status column as 'Overdue' in red font and the Next Dose Recommended column as 'Today'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn  vaccineName1, overdue
		
		Log "VERIFICATION: Ensure Next Dose Recommended column displays as 'Today'."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyNextRecommendedColumn vaccineName1, "Today"
		CaptureScreen(Name:"Step"&Global stepNumber&"-Workflow mPage")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Immunization Forecaster."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		
		Log "VERIFICATION: Ensure Varicella vaccine displays under CDC schedule column and 'Not Started' displays below the vaccine group name." 
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText  vaccineName1 & return & notStarted, columnSearchRectangle 
		
		Log "VERIFICATION: Ensure Dose 1 displayed in Red text in Today's column."
		set vaccineName1RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyText "Dose 1","Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Forecaster-Forecast/Validations".verifyDoseInRed(vaccineName1)
		
		Set startDateHeader to "Immunizations/Util/Date".todaysDate(format)+1 day
		Set endDateHeader to "Immunizations/Util/Date".todaysDate(format)+1 day
		Set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, -15, -15, 200, 900)
		run "Immunizations/Util/Validation".VerifyText forecastSuspended,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Initial Forecaster")
		---------------------------------------------------------------------------------------------------------------
		Log "Util".stepNumber & "ACTION: Chart Dose 1 using ProQuad with administration date as 12 months - 5 days from DOB."
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName1,dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)), Source, Product1, "Submit" 
		
		
		Log "VERIFICATION: Ensure the dose 1 displays charted with 'Did not count' icon with product name on top along with administration date(i.e. 12 months - 5 days from DOB)below it. "
		Set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5))
		Set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5))
		set vaccineName1RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-160", "-30", "100","100")
		run "Immunizations/Util/Validation".verifyText product1 &return& "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)) ,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyImage didNotCountImage,"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		set startDateHeader to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)), false, false)
		set endDateHeader to "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)), false, false)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-160", "-30", "100","100")
		run "Immunizations/Util/Validation".verifyText product1 &return& "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)),"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyImage didNotCountImage ,"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure a dose of MMR also gets charted with 'did not count' icon at 12 months - 5 days from DOB along with a dose of Varicella. Note: ProQuad is a combination vaccine for MMR and Varicella." 
		Set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5))
		Set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5))
		set vaccineName3RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName3)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-160", "-30", "100","100")
		run "Immunizations/Util/Validation".verifyText product1 &return& "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)) ,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName3RowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyImage didNotCountImage,"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName3RowSearchRectangle,columnSearchRectangle)
		
		set startDateHeader to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)), false, false)
		set endDateHeader to "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)), false, false)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-160", "-30", "100","100")
		run "Immunizations/Util/Validation".verifyText product1 &return& "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)),"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName3RowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyImage didNotCountImage ,"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName3RowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Did Not Count Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "ACTION: Click on Immunization Workflow MPage and select Varicella Vaccine, select the Modify button and modify Dose 1 <12 months - 5 days from DOB> to <12 months -4 days from DOB> and navigate back to the Forecaster view."
		run "Immunizations/Common/Actions".clickMPagesView viewPoint
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName1
		run "Immunizations/WorkFlowMPage/SidePanel/Task".modifyAdminDate "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-5)) ,1,dateFormat,"Immunizations/Util/Date".adjustDate(dob, format,("Month":12, "Day":-4)) 
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		
		Log "VERIFICATION: Ensure Varicella vaccine displays correctly with Last Admin:< date charted (DOB + 12 months- 4 days) > and Patient's age at the time of administration is displayed below the vaccine name under CDC Schedule column."
		set vaccineName1RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		Set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText lastAdmin &&  "Immunizations/Util/Date".adjustDate(dob,format,("Month":12, "Day":-4)) &&  "Immunizations/Util/Date".ageCalculator (dob,  "Immunizations/Util/Date".adjustDate(dob,format,("Month":12, "Day":-4)), false, true),"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure the dose 1 displays charted with with product name on top along with dose number and administration date(i.e. 12 months - 4 days from DOB)below it. "
		Set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4))
		Set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-140", "-30", "100","100")
		run "Immunizations/Util/Validation".verifyText product1 &return& "Dose 1" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4)) ,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		set startDateHeader to "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4)), false, false)
		set endDateHeader to "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4)), false, false)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-140", "-30", "100","100")
		run "Immunizations/Util/Validation".verifyText product1 &return& "Dose 1" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4)) ,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure a dose of MMR also gets charted with at 12 months - 4 days from DOB along with a dose of Varicella. Note: ProQuad is a combination vaccine for MMR and Varicella." 
		Set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4))
		Set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4))
		set vaccineName3RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName3)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-140", "-30", "100","100")
		run "Immunizations/Util/Validation".verifyText Product1 &return& "Dose 1" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4)) ,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName3RowSearchRectangle,columnSearchRectangle)
		
		set startDateHeader to "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4)), false, false)
		set endDateHeader to "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4)), false, false)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-140", "-30", "100","100")
		run "Immunizations/Util/Validation".verifyText product1&return& "Dose 1" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4)) ,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName3RowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure Dose 2 displays in today's column."
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyText "Dose 2","Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Dose 1 Forecaster Validation") 
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Dose 1 in the timeline to open the expanded view of the vaccine."
		Set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4))
		Set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-160", "-30", "100","100")
		Click text: "Dose 1", searchrectangle:"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure the left-hand pane, Dose 1 displays along with the Product name on the top along with Administration date dated from 12 months -4 days from DOB and age within parenthesis."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("1")
		run "Immunizations/Util/Validation".verifyText Product1 & return & "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4))&& "Immunizations/Util/Date".ageCalculator (dob,  "Immunizations/Util/Date".adjustDate(dob,format,("Month":12, "Day":-4)), false, true),rectangle
		
		Log "VERIFICATION: Ensure in the right-hand pane, all the details charted for the vaccine displays correctly."
		Set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText "Administered On" && "Immunizations/Util/Date".AdjustDate(dob, format,("Month":12, "Day":-4)) && "-" && Product1 , rightPaneHeaderSearchRectangle 
		
		Log "VERIFICATION: Performed date displays in the right hand column"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField performedDateField,"Immunizations/Util/Date".AdjustDate(dob, format, ("Month":12, "Day":-4)) 
		
		Log "VERIFICATION: User displays in the right hand colum."
		run  "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField  userField, user
		
		Log "VERIFICATION: Source displays in the right hand colum."
		run  "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField  sourceField, Source
		
		Log "VERIFICATION: Documented date displays in the right hand colum."
		run  "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField  documentedDateField,"Immunizations/Util/Date".todaysDate(format)
		
		Log "VERIFICATION: ProductName displays in the right hand colum."
		run  "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField  productNameField, Product1
		CaptureScreen(Name:"Step"&Global stepNumber&"-Dose 1 View Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Dose 2."
		click text:"2", searchrectangle:"Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchrectangle()
		
		Log "VERIFICATION: Ensure in the left pane, Dose 2 displays Due with Recommended from Age (4 years from DOB) below it."
		set leftPaneHeaderSearchectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("2")
		run "Immunizations/Util/Validation".verifyText "Due" & return & "Immunizations/Util/Date".adjustDate(dob, format, ("Year":4)), leftPaneHeaderSearchectangle
		
		Log "VERIFICATION: Ensure in the right-hand pane, dose 2 displays on the top."
		run "Immunizations/Util/Validation".verifyText "Dose 2", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION:  Earliest: 15 months from DOB."
		set age to "Immunizations/Util/Date".ageCalculator(dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":15)), false, true)
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField Minimum,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":15))&&age
		
		Log "VERIFICATION: Recommended From: 4 years from DOB."
		set age to "Immunizations/Util/Date".ageCalculator(dob, "Immunizations/Util/Date".adjustDate(dob, format, ("year":4)), false, true)
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended,"Immunizations/Util/Date".adjustDate(dob, format, ("year":4))&&age
		
		Log "VERIFICATION: Recommended From:  7 years + 4 weeks- 1 day from DOB.."
		set age to "Immunizations/Util/Date".ageCalculator(dob, "Immunizations/Util/Date".adjustDate(dob, format, ("year":7,"Week":4, "Day":-1)), false, true)
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended,"Immunizations/Util/Date".adjustDate(dob, format, ("year":7,"Week":4, "Day":-1))&&age
		
		Log "VERIFICATION:  Latest: --. "
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewFieldImage maximum, doubleDashImage
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Dose 2 Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION:Exit out of the expanded view and  Chart Dose 2 using Varivax with administration date as 13 months from DOB."
		Click text:"Print", searchrectangle: "Immunizations/Common/Helpers".tabListSearchRectangle
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName1, dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13)), Source, product2, "Submit"
		
		Log "VERIFICATION: Ensure CDC schedule column displays with a status of 'Complete' under Varicella Vaccine."
		Set columnSearchrectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText  vaccineName1 &return& complete, columnSearchRectangle
		
		Log "VERIFICATION: Ensure Dose 2 displays charted with product name on the top along with dose number and administration date dated from 13 months from DOB below it."
		Set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		Set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13))
		Set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13))
		Set vaccineName1RowSearchrectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText product2 &return& "Dose 2" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13)),"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchrectangle,columnSearchRectangle)
		
		Set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set startDateHeader to "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":13)), false, false)
		set endDateHeader to "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":13)), false, false)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText product2 &return& "Dose 2" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13)) ,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchrectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Forecaster View Dose2 Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Dose 2 in the timeline to open the expanded view of the vaccine."
		Set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		Set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13))
		Set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		Click text: "Dose 2", searchrectangle:"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure the left-hand pane, Dose 2 displays as Product name on the top along with Administration date dated from 13 months forn DOB and Patient's age within parenthesis."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("2")
		run "Immunizations/Util/Validation".verifyText product2 & return & "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13))&& "Immunizations/Util/Date".ageCalculator (dob,"Immunizations/Util/Date".adjustDate(dob, format, ("Month":13)), false, true),rectangle
		
		Log "VERIFICATION: Ensure in the right-hand pane, all the details charted for the vaccine displays correctly."
		Set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText "Administered On" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13)) && "-" && product2 , rightPaneHeaderSearchRectangle 
		
		Log "VERIFICATION: Performed date displays in the right hand column"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField performedDateField,"Immunizations/Util/Date".AdjustDate(dob, format, ("Month":13)) 
		
		Log "VERIFICATION: User displays in the right hand colum."
		run  "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField  userField, user
		
		Log "VERIFICATION: Source displays in the right hand colum."
		run  "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField  sourceField, Source
		
		Log "VERIFICATION: Documented date displays in the right hand colum."
		run  "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField  documentedDateField,"Immunizations/Util/Date".todaysDate(format)
		
		Log "VERIFICATION: ProductName displays in the right hand colum."
		run  "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField  productNameField, Product2
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Dose2 Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on list view"
		Click text:"Print", searchrectangle: "Immunizations/Common/Helpers".tabListSearchRectangle
		run "Immunizations/Forecaster-Common/Actions".clickFlipViews 
		
		Log "VERIFICATION: Ensure Varicella shows in the vaccine column with a status of 'Complete'."
		set vaccineName1RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".largeFirstColumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName1 &return& complete, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName1RowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: In the action column 1, ensure dose 1 displays for Varicella <DOB + 12 months- 4 days >(11m 3w)."
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchrectangle("1")
		set age to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format,("month": 12,"day":-4)), false, true)
		run "Immunizations/Util/Validation".VerifyText "1" && product1 &return&"Immunizations/Util/Date".adjustDate(dob, format,("month": 12,"day":-4))&& age ,"Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: In the action column 2, ensure dose 2 displays for Varicella <DOB + 13 months>."
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchrectangle("2")
		set age to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format,("month": 13)), false, true)
		run "Immunizations/Util/Validation".verifyText "2" & product2 &return& "Immunizations/Util/Date".adjustDate(dob, format, ("month": 13))&& age, "Immunizations/WorkflowMPage/Table/Helpers".CellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-List View Validation") 
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Immunization workflow MPage."
		run "Immunizations/Common/Actions".clickMPagesView viewPoint
		
		Log "VERIFICATION: Verify Varicella Vaccine displays in History section with status 'Complete'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameColumn vaccineName1
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameHistorySection vaccineName1
		
		Log "VERIFICATION: Ensure the status for Varicella displays as complete."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyStatusColumn vaccineName1, complete
		
		Log "VERIFICATION: Verify the Administrations displays 2."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyAdministrationColumn vaccineName1, "2"
		
		Log "VERIFICATION: Verify Next Dose Recommended displays '--'."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyNextRecommendedColumn vaccineName1, doubleDashImage
		
		Log "VERIFICATION: Verify Last Action column displays 'Administered'."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyLastActionColumn vaccineName1, administered
		
		Log "VERIFICATION: Verify Last Action Date column displays with the last charting event date."
		Set lastActionDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13))
		set age to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format,("month": 13)), false, false)
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyLastActionDateColumn vaccineName1, uppercase(lastActionDate), age
		CaptureScreen(Name:"Step"&Global stepNumber&"-WorkFlow MPage Validation") 
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Unchart Dose 2 for Varicella Vaccine."
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName1
		run  "Immunizations/WorkflowMPage/SidePanel/Task".unchart "Immunizations/Util/Date".adjustDate(dob, format, ("Month":13)),1,unchartedReason
		
		Log "VERIFICATION: Verify Varicella Vaccine does not display in the History section."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameAboveHistorySection vaccineName1
		
		Log "VERIFICATION: Ensure the status for Varicella displays as 'In Range'.'"
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyStatusColumn vaccineName1, inRange
		CaptureScreen(Name:"Step"&Global stepNumber&"-WorkFlow MPage In Range Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Chart a Dose selecting Zoster vaccine and chart administration at 4 years from DOB using the product Zoster Vaccine Live(121)."
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName2,dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("Year":4)), Source, Product3, "Submit"
		
		Log "VERIFICATION: Verify Varicella Vaccine displays in History section with status 'Complete'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameHistorySection vaccineName1
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyStatusColumn vaccineName1, complete
		
		Log "VERIFICATION: Verify the Administrations displays 2."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyAdministrationColumn vaccineName1, "2"
		
		Log "VERIFICATION: Verify Next Dose Recommended displays '--'."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyNextRecommendedColumn vaccineName1, doubleDashImage
		CaptureScreen(Name:"Step"&Global stepNumber&"-WorkFlow MPage Zoster Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Immunization Forecaster link and review CDC schedule column for Varicella vaccine."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		run "Immunizations/Forecaster-Common/Actions".clickFlipViews
		
		Log "VERIFICATION: Verify Varicella vaccine status is 'Complete' under CDC schedule column." 
		set vaccineName1RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		Set columnSearchrectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText  vaccineName1 &return& complete, columnSearchRectangle  
		
		Log "VERIFICATION: Verify dose charted for Zoster vaccine live is displayed under Varicella Vaccine timeline as Dose 2."
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyText product3 &return& "Dose 2" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Year":4)),"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Forecaster Complete Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Immunization Workflow Mpage and Unchart dose 2 charted for Zoster."
		run "Immunizations/Common/Actions".clickMPagesView viewPoint
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName2
		run  "Immunizations/WorkflowMPage/SidePanel/Task".unchart "Immunizations/Util/Date".adjustDate(dob, format, ("Year":4)),1,unchartedReason
		
		Log "VERIFICATION: Verify Varicella Vaccine does not display in the History section."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameAboveHistorySection vaccineName1
		
		Log "VERIFICATION: Ensure Varicella displays with status 'In Range'."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyStatusColumn vaccineName1,inRange
		
		Log "VERIFICATION: Verify the Administrations displays 1."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyAdministrationColumn vaccineName1, "1"
		
		Log "VERIFICATION: Next Dose Recommended displays as 'Today - Recommended Until (7 years + 4 weeks -1 day from DOB)'."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyNextRecommendedColumn vaccineName1, "Today" && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Year":7, "Week":4, "Day":-1))
		
		Log "VERIFICATION: Verify Last Action column displays 'Administered'."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyLastActionColumn vaccineName1, administered
		
		Log "VERIFICATION: Verify Last Action Date column displays with the last charting event date."
		Set lastActionDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12, "Day":-4))
		set age to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format,("Month":12, "Day":-4)), false, false)
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyLastActionDateColumn vaccineName1, uppercase(lastActionDate), age
		CaptureScreen(Name:"Step"&Global stepNumber&"-MPage Zoster Uncharted Validation")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Immunization Forecaster and review Varicella and Zoster vaccines."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		
		Log "VERIFICATION: Verify that under varicella vaccine dose 2 displays under Today's column."
		set vaccineName1RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyText "Dose 2","Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName1RowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Verify Zoster is displayed and is uncharted with administered date and paper clip icon on top right."
		run "Immunizations/Forecaster-Forecast/Actions".clickScrollDownArrow
		set vaccineName2RowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName2)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
		run "Immunizations/Util/Validation".verifyText uncharted &return& "Immunizations/Util/Date".adjustDate(dob, format, ("Year":4)), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName2RowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyImage unchartIconImage,"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineName2RowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Forecaster Zoster Uncharted Validation")
		---------------------------------------------------------------------------------------------------------------
		
		log "Util".stepNumber &"ACTION: Close Application."
		run "Immunizations/Setup".closeApplication 
		---------------------------------------------------------------------------------------------------------------
		
		EndTestCase "HLM-VR-Immunizations-Varicella_Overdue"
		
	catch
		logError "Test Steps Exception: " && the exception.reason
		captureScreen "PWF_Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
	end try
	#PATIENT CLEANUP
	log "ACTION: Cleanup Patient."
	run "Immunizations/PatientCreation".openPMLaunch nonDbaUserName, password, domain
	run "Immunizations/PatientCreation".openConversation conversation
	run "Immunizations/PatientCreation".searchPatient lastName,firstName
	run "Immunizations/PatientCreation".renamePatientSearched newLastName
	run "Util".closeApplication 2
	---------------------------------------------------------------------------------------------------------------
catch
	logError "Exception encountered: " && the exception.reason
	captureScreen "Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
end try
---------------------------------------------------------------------------------------------------------------
#SUT CLEANUP
run "Cleanup".ZeroStateCloseAllApps