-------------------------------------------------Helper Suite Information-------------------------------------------

#https://github.cerner.com/EggPlant/IPDev-Shared-Millennium
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-Immunizations
#https://github.cerner.com/EggPlant/IPDev-Millennium-Shared-HealthMaintenanceTools
# https://github.cerner.com/EggPlant/IPDev-Shared-Utilities
------------------------------------------------------------------------------------------------------------------------------

#RQM TEST CASE LINK: https://jazz.cerner.com:9443/qm/web/console/IP#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestCase&id=121644
params domain 

set domain to "Immunizations/Util/Setup".domainRun(domain)
set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set relationship to setup.relationship
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set username to setup.username
set password to decodeText(setup.("password").trimAll, "HLM")

set common to JSONValue(file resourcePath("common.json"))
set menu to common.menu
set subMenu to common.subMenu
set viewpoint to common.viewpoint
set doubleDashImage to common.doubleDashImage
set didNotCountImage to common.didNotCountImage

set fieldLabels to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("fieldLabels.json")),domain)
set minimum to fieldLabels.minimum
set earliestRecommended to fieldLabels.earliestRecommended
set latestRecommended to fieldLabels.latestRecommended
set maximum to fieldLabels.maximum

set textStrings to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("textStrings.json")),domain)
set viewForecast to textStrings.viewForecast
set notStarted to textStrings.notStarted
set lastAdmin to textStrings.lastAdmin
set notDueUntil to textStrings.notDueUntil

set testData to JSONValue(file ResourcePath("VR/DTaP_Vaccine_Forecast/testData.json"))
set dateFormat to testData.dateFormat

set testData to JSONValue(file resourcePath("VR/DTaP_Vaccine_Forecast/testData.json")).(value of domain)
set patientName to testData.Patient5.nameFullFormatted
set firstName to testData.Patient5.firstName
set lastName to testData.Patient5.lastName
set dob to formattedTime("%m/%d/%Y", value(testData.Patient5.dob))
set vaccineName1 to testData.vaccineName1
set vaccineName6 to testData.vaccineName6
set vaccineName7 to testData.vaccineName7
set source to testData.source
set product2 to testData.product2
set product8 to testData.product8
set product9 to testData.product9
set user to testData.user
set format to "%b %d, %Y"


try	
	#PATIENT RESET
	run "Immunizations/PatientCreation".resetPatientToZeroState username, password, domain, lastName, firstName, dob
	
	Try
		Log "Util".stepNumber & "ACTION: Launch Powerchart.exe with User1. Search and select Patient1. Select Immunization workflow MPage from the TOC and navigate to Immunization section."
		run "Immunizations/setup".loginAndLoadcomponentViaMenu username, password, domain, patientName, menu, subMenu,relationship
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast viewForecast
		
		Log "VERIFICATION: Ensure the Forecaster loads."
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText  vaccineName1 & return & notstarted, columnSearchRectangle 
		CaptureScreen(Name:"Step"&Global stepNumber&"-Initial Forecaster Patient5")
		---------------------------------------------------------------------------------------------------------------
		Log "Util".stepNumber & "ACTION: Chart 2 administrations for DTaP (one with an admin date of DOB + 2 months and one with an admin date of DOB + 4 months)."
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName1, dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), source , product2, "Submit"
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName1, dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), source , product2, "Submit"
		
		Log "VERIFICATION: Under CDC Schedule Column, vaccine group name displays at the top along with Last Admin:< date charted (DOB + 4 months) > with age at the time in parentheses."
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText lastAdmin && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)) && "(4m)", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Ensure Dose 1 displays charted in the timeline with the product name and dose number along with Administration date on the DTaP row in the column dated for 2 months from DOB. "
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2))
		set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText product2 &return&"Dose 1 -"&&"Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure Dose 1 displays charted in the timeline with the product name and dose number along with Administration date on the DTaP row in the column for age 2 months. "
		set startDateHeader to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), "false", "false")
		set endDateHeader to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), "false", "false")
		set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText product2 &return&"Dose 1 -"&&"Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure Dose 2 displays charted in the timeline with the product name and dose number along with Administration date on the DTaP row in the column dated for 4 months from DOB. "
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4))
		set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText product2 &return&"Dose 2 -"&&"Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure Dose 2 displays charted in the timeline with the product name and dose number along with Administration date on the DTaP row in the column for age 4 months. "
		set startDateHeader to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "false", "false")
		set endDateHeader to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "false", "false")
		set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText product2 &return&"Dose 2 -"&&"Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Verify Dose 3 is displayed in the timeline to the right in the column dated for 6 months to 7 months + 4 weeks - 1 day." 
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":7, "Week":4, "Day":-1))
		set alignment to ("Left","Right")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2,format)
		run "Immunizations/Util/Validation".verifyText "Dose 3", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Verify Dose 3 is displayed in the timeline to the right in the column for 6 months to 7 months + 4 weeks - 1 day." 
		set alignment to ("Left","Right")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set startDateHeader to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6)), "false", "false")
		set endDateHeader to "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":7,"Week":4,"Day":-1)), "false", "false")
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText "Dose 3", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Dose 3 Forecast after 1,2 dose for Patient5")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Chart an administration of MMR between 26 days and 1 day less than the administration for Dose 2 of DTaP (e.g. DOB + 4 months – 1 week)."
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName6 , dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1)), source , product8 , "Submit"
		
		Log "VERIFICATION: Ensure the administration for MMR charted."
		run "Immunizations/Forecaster-Forecast/Actions".scrollToLeft
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"week":-1)), "false", "true")
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName6)
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText "Last Admin:" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1)) && age, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		//Did Not Count Icon Verification
		run "Immunizations/Util/Validation".verifyImage didNotCountImage,"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure administration displays charted in the timeline with the product name or default event set name (if charting without a product) and Administration date on the MMR row in the column dated for 4 months - 1 week from DOB. "
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-75","-75","85","600")
		set rectangle to "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText product8 &return&"Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1)), rectangle
		run "Immunizations/Util/Validation".verifyImage didNotCountImage,rectangle
		CaptureScreen(Name:"Step"&Global stepNumber&"-MMR Charted Patient5")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Chart an administration for Varicella less than 28 days from the administration of MMR (e.g. DOB + 4 months – 1 week + 27 days)"
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName7, dateFormat, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1,"Day":27)), source, product9, "Submit"
		
		Log "VERIFICATION: Ensure the administration for Varicella charted."
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"week":-1,"Day":27)), "false", "true")
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName7)
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText lastAdmin && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1,"Day":27)) && age, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		//Did Not Count Icon Verification
		run "Immunizations/Util/Validation".verifyImage didNotCountImage,"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Ensure administration displays charted in the timeline with the product name or default event set name (if charting without a product) and Administration date on the Varicella row in the column dated for 4 months - 1 week from DOB. "
		run "Immunizations/Forecaster-Forecast/Actions".scrollToLeft
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1,"Day":27))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1,"Day":27))
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle("Varicella")
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,"-75","-75","85","600")
		run "Immunizations/Util/Validation".verifyText product9 &return&"Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":-1,"Day":27)), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		//Did Not Count Icon Verification
		set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyImage didNotCountImage,"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Dose 1 and Dose 2 of DTaP display as charted in the timeline to the right with the product selected or event set name on the top."
		//Dose 1
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2))
		set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText product2 &return&"Dose 1 -"&&"Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		//Dose 2
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4))
		set alignment to ("Center","Center")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText product2 &return&"Dose 2 -"&&"Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Verify Dose 3 for DTaP is displayed in the timeline to the right in the column for 6 months to 7 months + 4 weeks - 1 day." 
		set alignment to ("Left","Right")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":7, "Week":4, "Day":-1))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		run "Immunizations/Util/Validation".verifyText "Dose 3", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Varicella Charted Patient5")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click on Dose 3 of DTaP"
		if imageFound("Immunizations/Setup/Server_down_error")
			logWarning "Bypassing a server error not related to our solution: https://jira2.cerner.com/browse/IMMUN-1802"
			click image:"Immunizations/Setup/Button_Close"
			wait 1
		end if
		set alignment to ("Left","Right")
		set (topOffset1,topOffset2,bottomOffset1,bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set startDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6))
		set endDateHeader to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":7, "Week":4, "Day":-1))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader,endDateHeader,topOffset1,topOffset2,bottomOffset1,bottomOffset2)
		Click text: "Dose 3",searchRectangle:"Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchrectangle,columnSearchrectangle)
		
		Log "VERIFICATION: Ensure the charted details for Dose 1 and Dose 2 display within expanded view with the product selected and date adminstered."
		//Dose 1
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), "false", "true")
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("1")
		run "Immunizations/Util/Validation".verifyText product2 & return & "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2))&&age, rectangle
		//Dose 2
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "false", "true")
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("2")
		run "Immunizations/Util/Validation".verifyText product2 & return & "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4))&&age, rectangle
		
		Log "VERIFICATION: In the left-hand pane, Dose 3 displays as Not Due Until at the top and Recommended From date below it (+ 6 months from DOB)"
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("3")
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6)), rectangle
		
		//Expanded view header validation
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle()
		run "Immunizations/Util/Validation".verifyText "Dose 3", rectangle
		//Expanded view body validation
		Log "VERIFICATION: Earliest: + 4 weeks from Dose 2 (+ 4 months + 4 weeks from DOB)"
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"week":4)), "false", "true")
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4,"Week":4)) &&age
		
		Log "VERIFICATION: Recommended From: + 6 months from DOB."
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6)), "false", "true")
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6)) &&age
		
		Log "VERIFICATION: Recommended Until: + 7 months + 4 weeks - 1 day from DOB."
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":7,"week":4,"Day":-1)), "false", "true")
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":7, "Week":4, "Day":-1)) &&age
		
		Log "VERIFICATION: Latest: '--'"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewFieldImage maximum, doubleDashImage
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Dose 3 Patient5")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Click outside expanded view and click the List button."
		Set topPaneRectangle to "Immunizations/Common/Helpers".tabListSearchrectangle
		Click text:"Print", searchrectangle:topPaneRectangle
		run "Immunizations/Forecaster-Common/Actions".ClickFlipViews
		
		Log "VERIFICATION: Within the first column the vaccine group name displays at the top along with Last Admin:< date charted (DOB + 4 months) > with age at the time in parentheses."
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "false", "true")
		set rowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
		set columnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText "Last Admin:" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)) && age, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Verify Dose 1 of DTaP displays with the product and administration date charted in the Action column"
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), "false", "true")
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchRectangle("1")
		run "Immunizations/Util/Validation".verifyText "1"&& product2, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2))&& age, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		
		Log "VERIFICATION: Verify Dose 2 of DTaP displays with the product and administration date charted in the Action column"
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "false", "true")
		set columnSearchRectangle to "Immunizations/Forecaster-List/Helpers".columnSearchRectangle("2")
		run "Immunizations/Util/Validation".verifyText "2" && product2, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4))&& age, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle,columnSearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-List View Patient5")
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "ACTION: Navigate to the Immunizations Workflow component."
		run  "Immunizations/Common/Actions".clickMPagesView (viewPoint)
		
		Log "VERIFICATION: Administration column displays 2 for DTaP."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyAdministrationColumn vaccineName1, "2"
		
		Log "VERIFICATION: Next Dose Recommended column displays Recommended From (6 months from DOB) - Recommended Until (7 months + 4 weeks - 1 day from DOB)."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyNextRecommendedColumn vaccineName1, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6)) && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month":7, "Week":4, "Day":-1))
		
		Log "VERIFICATION: Last Action column displays 'Administered'."
		run "Immunizations/WorkflowMPage/Table/Validations".VerifyLastActionColumn vaccineName1,"Administered"
		---------------------------------------------------------------------------------------------------------------
		
		Log "Util".stepNumber & "Click on DTaP"
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName1
		
		Log "VERIFICATION: within the side panel the administration dates (DOB + 4 months and DOB + 2 months) with 'Administered' display for charted doses 1 and 2."
		//Dose 1
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)), "false", "true")
		set sidePanelRectangle to "Immunizations/WorkflowMPage/SidePanel/Helpers".SidePanelRectangle
		run "Immunizations/WorkflowMPage/SidePanel/Validations".lastActionWithIndex "1", "Documented By", sidePanelRectangle, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)) && age && "-" && "Administered"
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "1", "Documented By", sidePanelRectangle, user
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "1", "Source", sidePanelRectangle, source
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "1", "Product", sidePanelRectangle, product2
		//Dose 2
		set age to  "Immunizations/Util/Date".ageCalculator (dob, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)), "false", "true")
		run "Immunizations/WorkflowMPage/SidePanel/Validations".lastActionWithIndex "2", "Documented By", sidePanelRectangle, "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)) && age && "-" && "Administered"
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "2", "Documented By", sidePanelRectangle, user
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "2", "Source", sidePanelRectangle, source
		run "Immunizations/WorkflowMPage/SidePanel/Validations".verifyFieldValue "2", "Product", sidePanelRectangle, product2
		CaptureScreen(Name:"Step"&Global stepNumber&"-mPage DTaP Dose 1 and 2 Patient5")
		---------------------------------------------------------------------------------------------------------------
	Catch theException
		logError "Exception encountered" && theException.reason
		captureScreen "Exception" & formattedTime("_%m%d%Y%H%M%S", the time)
	end try
	---------------------------------------------------------------------------------------------------------------
	
	Log "Util".stepNumber & "Close Patient's chart."
	run "Immunizations/setup".closeChartViaX
	---------------------------------------------------------------------------------------------------------------
	log "Util".stepNumber &"ACTION: Close patient's chart."
	run "Immunizations/setup".closeApplication 
	--------------------------------------------------------------------------------------------------------------- 
catch exception
	logError "Exception encountered" && exception.reason
	log "Exception Location:" && exception.location	
	captureScreen"Exception" && "at" & Global stepNumber
end try
run "Cleanup".ZeroStateCloseAllApps	