params domain

log "Test running in domain"&&domain
set domain to "Immunizations/Util/Setup".domainRun(domain)
log "After handler to set domain, domain is" && domain
set format to "%m/%d/%Y"

set testData to JSONValue(file resourcePath(ResourcePath("VR/ReconcileRegistryForecast/testData.json"))).(value of domain)

set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
set username to setup.username
set password to decodeText(setup.("password").trimAll, "HLM")
set conversation to setup.conversation
set encounterOrg to setup.encounterOrg
set encounterType to setup.encounterType

log "Create patient1 "& age &" for the test"
run "Immunizations/PatientCreation".openPMLaunch username, password, domain
run "Immunizations/PatientCreation".openConversationContinuous conversation

set lastName to testData.Patient1.lastName
set firstName to testData.Patient1.firstName
set dob to formattedTime(format, value(testData.Patient1.dob)) 
set sex to testData.Patient1.sex
run "Immunizations/PatientCreation".searchPatient lastName, firstName
run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, format, dob, encounterType
---------------------------------------------------------------------------------------------------------------
set lastName to testData.Patient2.lastName
set firstName to testData.Patient2.firstName
set dob to formattedTime(format, value(testData.Patient2.dob)) 
set sex to testData.Patient2.sex
log "Create patient2 "& age &" for the test"
run "Immunizations/PatientCreation".searchPatient lastName, firstName
run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, format, dob, encounterType
----------------------------------------------------------------------------------------------------------------
set lastName to testData.Patient3.lastName
set firstName to testData.Patient3.firstName
set dob to formattedTime(format, value(testData.Patient2.dob)) 
set sex to testData.Patient3.sex
log "Create patient3 "& age &" for the test"
run "Immunizations/PatientCreation".searchPatient lastName, firstName
run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, format, dob, encounterType
----------------------------------------------------------------------------------------------------------------
run "Util".closeApplication 2