Params domain
set domain to "Immunizations/Util/Setup".domainRun(domain)
Log "Test running in domain"&&domain

set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
Log "commonData:" && setup
Set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
Set relationship to setup.relationship

Set common to JSONValue(file resourcePath("Common.json"))
Set menu to common.menu
Set subMenu to common.subMenu
Set doubleDashImage to common.doubleDashImage

set fieldLabels to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("fieldLabels.json")),domain)
Set minimum to fieldLabels.minimum
Set earliestRecommended to fieldLabels.earliestRecommended
Set latestRecommended to fieldLabels.latestRecommended
Set maximum to fieldLabels.maximum

set textStrings to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("textStrings.json")),domain)
Set viewForecast to textStrings.viewForecast
Set notStarted to textStrings.notStarted
Set immunizationForecast to textStrings.immunizationForecast
Set notDueUntil to textStrings.notDueUntil
Set earliestRecommendedWithoutColon to textStrings.earliestRecommendedWithoutColon
Set inRange to textStrings.inRange
Set inRangeToday to textStrings.inRangeToday
Set due to textStrings.due

Set testData to JSONValue(file ResourcePath("VR/Tdap_Vaccine_Conditional_Forecast/testData.json")).(value of domain)
Set patientName to testData.Patient4.nameFullFormatted
Set dob to formattedTime("%m/%d/%Y", value(testData.Patient4.dob)) 
Set vaccineName1 to testData.vaccineName1
Set vaccineName2 to testData.vaccineName2
Set vis1 to testData.vis1
Set vis2 to testData.vis2
Set vis3 to testData.vis3
Set source to testData.source
Set dtapProduct1 to testData.dtapProduct1

Set format to "%b %d, %Y"



Try	
	---------------------------------------------------------------------------------------------------------------
	Log "PRECONDITION: Patient4 – Exactly 7 years old. Has received 2 valid doses of DTaP in the past between the ages of 1 and 7 years minus 4 weeks. Does not have any charted events for Td/Tdap."
	Run "Immunizations/Setup".NavigateToImmunizationWorkflowViaMenu patientName, menu, subMenu, relationship
	Run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName2, "Date", "Immunizations/Util/Date".adjustDate(dob, format, ("Month":15)), source, dtapProduct1, "Submit"
	Run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName2, "Date", "Immunizations/Util/Date".adjustDate(dob, format, ("Year":4)), source, dtapProduct1, "Submit"
	
	---------------------------------------------------------------------------------------------------------------
	
	Log "Util".stepNumber & "ACTION:  open Patient 4's chart and open the Immunization Workflow Mpage"
	Log "INFORMATION: Already in Workflow MPage."
	
	Log "VERIFICATION: Ensure Patient4's chart opens without any errors."
	Run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameColumn vaccineName1
	
	Log "VERIFICATION: Verify the following for Td/Tdap: Status column displays In Range."
	Run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName1, inRange
	
	Log "VERIFICATION: Vaccine column displays vaccine group name (Td/Tdap)."
	Run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameColumn vaccineName1
	
	Log "VERIFICATION: Doses Admin., Last Action Date, and Last Action columns display a double dash."
	Run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName1, "--", false
	Run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionDateColumn vaccineName1, "--"
	Run "Immunizations/WorkflowMPage/Table/Validations".verifyLastActionColumn vaccineName1, "--"
	
	Log "VERIFICATION: Next Dose Recommended column displays Today."
	Run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName1,"Today"
	CaptureScreen(Name: "Step" & Global stepNumber & "-WorkflowMpageOpenPowerchart-P4")
	---------------------------------------------------------------------------------------------------------------
	
	Log "Util".stepNumber & "ACTION: Click on Td/Tdap."
	Run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName1
	
	Log "VERIFICATION: Ensure side panel displays. Ensure the Vaccine group name displays on the first line."
	Set sidePanelHeaderRectangle to "Immunizations/WorkflowMPage/SidePanel/Helpers".sidePanelTopHeaderRectangle()
	Run "Immunizations/Util/Validation".verifyText vaccineName1, sidePanelHeaderRectangle
	
	Log "VERIFICATION: The status (In Range) with the Next Dose Recommended date (Today) displays in parenthesis on the second line above the side panel header line."
	Run "Immunizations/WorkflowMPage/Sidepanel/Validations".verifyValidNextRecommendedDate inRange && "-" && "Today", sidePanelHeaderRectangle
	CaptureScreen(Name: "Step" & Global stepNumber & "-WFMpageVacSidePanel-P4")
	---------------------------------------------------------------------------------------------------------------
	
	Log "Util".stepNumber & "ACTION: Click on the View Forecast link."
	Run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast (viewForecast)
	
	Log "VERIFICATION: Ensure the Immunization Forecaster (Forecast tab) opens as a new tab without any errors within the MPage. Ensure the CDC Schedule column displays on the far left."
	Run "Immunizations/Util/Validation".verifyText immunizationForecast, "Immunizations/Common/Helpers".tabListSearchRectangle()
	Set columnSearchrectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
	Run "Immunizations/Util/Validation".verifyText  vaccineName1, columnSearchRectangle
	
	Log "VERIFICATION: Verify the Today Column displays highlighted in Yellow with Dose 1 in black text displays."
	Run "Immunizations/Util/Validation".verifyImage "Immunizations/Forecaster-Forecast/Search/TL_Today/GreyToOrange_SOLGM2012_6.9"
	Set rowSearchrectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName1)
	Set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangleToday()
	Run "Immunizations/Util/Validation".verifyText "Dose 1", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, columnSearchRectangle)
	Run "Immunizations/Forecaster-Forecast/Validations".verifyDoseInBlack(vaccineName1)
	
	Log "VERIFICATION: Ensure below the Vaccine name, Not Started is displayed."
	Set firstColumnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstColumnSearchRectangle()
	Run "Immunizations/Util/Validation".verifyText vaccineName1 &return& notStarted, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(rowSearchRectangle, firstColumnSearchRectangle)
	CaptureScreen(Name: "Step" & Global stepNumber & "-ForecastTimeline-P4")
	---------------------------------------------------------------------------------------------------------------
	
	Log "Util".stepNumber & "ACTION: Click on the Vaccine header."
	Run "Immunizations/Forecaster-Forecast/Actions".clickVaccineName vaccineName1
	
	Log "VERIFICATION: Ensure the expanded view of the vaccine displays the following information: In the left pane header the vaccine group with Not Started below displays."
	Set leftPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneHeaderSearchRectangle
	Run "Immunizations/Util/Validation".verifyText vaccineName1 & return & notStarted, leftPaneHeaderSearchRectangle
	
	Log "VERIFICATION: In the left pane column Dose 1 displays with the status Due with the Recommended From date below, Dose 2 displays with the status Not Due Until with the Recommended From date below, and Dose 3 displays with the status of Not Due Until with the Recommended From date (+ 10 years after Dose 2's Recommended From date)."
	Set dose1RecommendedFromDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year":7))
	Set dose2RecommendedFromDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year":11))
	Set leftPaneSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers". expandedViewLeftPaneDoseSearchRectangle("1")
	Run "Immunizations/Util/Validation".verifyText due & return & dose1RecommendedFromDate, leftPaneSearchRectangle
	Set leftPaneSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers". expandedViewLeftPaneDoseSearchRectangle("2")
	Run "Immunizations/Util/Validation".verifyText notDueUntil & return & dose2RecommendedFromDate, leftPaneSearchRectangle
	
	Log "VERIFICATION: Ensure in the right pane header, Dose 1 Due Today – Td/Tdap displays on the first line and the Status (In Range) with the Next Dose Recommended date (Today) displays left aligned on the second line with Recommended From < Recommended From – Recommended Until dates > right aligned.Ensure Vaccine Information Statement(s): displays and below the link(s) to Vaccine Information Statement(s) for Td\Tdap is displayed"
	Set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle
	Run "Immunizations/Util/Validation".verifyText "Dose 1" && due && "Today" && "-" && vaccineName1, rightPaneHeaderSearchRectangle
	Run "Immunizations/Util/Validation".verifyText inRangeToday, rightPaneHeaderSearchRectangle
	Set recommendedDateRangeFormatted to "Immunizations/Util/Date".adjustDate(dob,"%m/%d/%y", ("Year":7)) && "-" && "Immunizations/Util/Date".adjustDate(dob, "%m/%d/%y", ("Year":7))
	Run "Immunizations/Util/Validation".verifyText earliestRecommendedWithoutColon && recommendedDateRangeFormatted, rightPaneHeaderSearchRectangle
	Set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle 
	Run "Immunizations/Util/Validation".verifyText vis1, rightPaneBodySearchRectangle
	Run "Immunizations/Util/Validation".verifyText vis2, rightPaneBodySearchRectangle
	Run "Immunizations/Util/Validation".verifyText vis3, rightPaneBodySearchRectangle
	CaptureScreen(Name: "Step" & Global stepNumber & "-ExpandedViewMain-P4")
	---------------------------------------------------------------------------------------------------------------
	
	Log "Util".stepNumber & "ACTION: Click on Dose 1 in the expanded view."
	Click text: "1", validWords:"*", SearchRectangle: "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchRectangle()
	
	Log "VERIFICATION: In the right hand pane, the header displays Dose 1 with the following details in the body."
	Run "Immunizations/Util/Validation".verifyText "Dose 1", rightPaneHeaderSearchRectangle
	
	Log "VERIFICATION: 1. Earliest: dated for 7 years from DOB with the age at the time of in parenthesis to the right."
	Run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose1RecommendedFromDate
	Set dose1RecommendedFromAge to "Immunizations/Util/Date".ageCalculator (dob, dose1RecommendedFromDate, false, false)
	Set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle()
	Run "Immunizations/Util/Validation".verifyTextWithPattern dose1RecommendedFromAge, "Immunizations/Util/Date".setPattern(dose1RecommendedFromAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
	
	Log "VERIFICATION: 2. Recommended From: dated for 7 years from DOB with the age at the time of in parenthesis to the right."
	Run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose1RecommendedFromDate
	Run "Immunizations/Util/Validation".verifyTextWithPattern dose1RecommendedFromAge, "Immunizations/Util/Date".setPattern(dose1RecommendedFromAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
	
	Log "VERIFICATION: 3. Recommended Until: dated for 7 years from DOB with the age at the time of in parenthesis to the right."
	Run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose1RecommendedFromDate
	Run "Immunizations/Util/Validation".verifyTextWithPattern dose1RecommendedFromAge, "Immunizations/Util/Date".setPattern(dose1RecommendedFromAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
	
	Log "VERIFICATION: 4. Latest: -- "
	Run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewFieldImage maximum, doubleDashImage
	CaptureScreen (Name: "Step" & Global stepNumber & "TdapForecastDose1-P4")
	---------------------------------------------------------------------------------------------------------------
	
Catch
	LogError "Exception encountered: " && the exception.reason
	captureScreen "Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
End Try
---------------------------------------------------------------------------------------------------------------
Log "Util".stepNumber &"ACTION: Close patient 4's chart."
Run "Immunizations/setup".closeChartViaX