--------------------------------------------------Helper Suite Information-------------------------------------------

#https://github.cerner.com/EggPlant/IPDev-Shared-Millennium
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-Immunizations
#https://github.cerner.com/EggPlant/IPDev-mPages-Shared-HealthMaintenanceTools
#https://github.cerner.com/EggPlant/IPDev-Shared-Utilities

------------------------------------------------RQM TEST CASE LINK--------------------------------------------------------

# https://jazz.cerner.com:9443/qm/web/console/IP#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewTestCase&id=62043

---------------------------------------Assigning Test Data to the Variables---------------------------------------

params domain
set domain to "Immunizations/Util/setup".domainRun(domain)
log "Test running in domain"&&domain
set format to "%b %d, %Y"

set setup to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("setup.json")),domain)
log "commonData:" && setup
set username to setup.username
set password to decodeText(setup.("password").trimAll, "HLM")
set the remoteWorkInterval to value(setup.("remoteWorkInterval"))
set relationship to setup.relationship
set conversation to setup.conversation
set encounterOrg to setup.encounterOrg
set encounterType to setup.encounterType

set common to JSONValue(file resourcePath("Common.json"))
set menu to common.menu
set subMenu to common.subMenu
set didNotCountImage to common.didNotCountImage
set doubleDashImage to common.doubleDashImage
set viewpoint to common.viewpoint

set fieldLabels to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("fieldLabels.json")),domain)
set minimum to fieldLabels.minimum
set earliestRecommended to fieldLabels.earliestRecommended
set latestRecommended to fieldLabels.latestRecommended
set maximum to fieldLabels.maximum

set textStrings to "UTIL_Json".initializeResourceData(JSONValue(file resourcePath("textStrings.json")),domain)
set viewForecast to textStrings.viewForecast
set notStarted to textStrings.notStarted
set immunizationForecast to textStrings.immunizationForecast
set lastAdmin to textStrings.lastAdmin
set notDueUntil to textStrings.notDueUntil
set earliestRecommendedWithoutColon to textStrings.earliestRecommendedWithoutColon

set testData to JSONValue(file resourcePath("VR/Pneumococcal_Standard_Series/testData.json"))
set dateFormat to testData.dateFormat

set testData to JSONValue(file resourcePath("VR/Pneumococcal_Standard_Series/testData.json")).(value of domain)
set patientName to testData.Patient1_Full_Forecast.nameFullFormatted
set lastName to testData.Patient1_Full_Forecast.lastName
set firstName to testData.Patient1_Full_Forecast.firstName
set newLastName to testData.Patient1_Full_Forecast.newLastName
set sex to  testData.Patient1_Full_Forecast.sex
set dob to formattedTime(format, value(testData.Patient1_Full_Forecast.dob)) 
set vaccineName to testData.vaccineName
set source to testData.source
set product1 to testData.product1
set vis to testData.vis



try
	------------------------------------------------------Patient Setup---------------------------------------------------------
	Log "PATIENT CREATION: Open PmLaunch and Create patient(s) of 6 weeks for the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".patientSearched encounterOrg, firstName, sex, "%m/%d/%Y", dob, encounterType
	run "Util".closeApplication 2
	----------------------------------------------------------------------------------------------------------------------------------
	try
		------------------------------------------------------Test Steps---------------------------------------------------------
		BeginTestCase "VR/Pnuemococcal/HLM-VR-Immunizations-Pneumococcal_Standard_Series_Full_Forecast_6_weeks_old"
		
		Log "Util".stepNumber &"ACTION: Open Patient1's chart and navigate to the Immunizations workflow mPage."
		run "Immunizations/setup".loginAndLoadcomponentViaMenu username, password, domain, patientName, menu, subMenu,  relationship
		
		Log "VERIFICATION: Pneumococcal Conjugate is displayed in the Vaccine column."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameColumn vaccineName
		
		Log "VERIFICATION: The status column for Pneumococcal Conjugate displays as '--'."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyStatusColumn vaccineName, doubleDashImage
		
		Log "VERIFICATION: The administrations column displays '--' for Pneumococcal Conjugate"
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, doubleDashImage, "false"
		
		Log "VERIFICATION: The Next Recommended column displays '< DOB + 2 months > – < DOB + 3 months + 4 weeks - 1 day >' for Pneumococcal Conjugate."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyNextRecommendedColumn vaccineName,  "Immunizations/Util/Date".adjustDate(dob, format, ("Month": 2)) && "-" && "Immunizations/Util/Date".adjustDate(dob, format, ("Month": 3, "Week":4, "Day":-1))
		
		Log "VERIFICATION: Pneumococcal Conjugate displays above the History section."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyVaccineNameAboveHistorySection vaccineName
		CaptureScreen(Name:"Step"&Global stepNumber&"-mPage Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on 'View Forecast'."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast (viewForecast)
		
		Log "VERIFICATION: The first column for Pneumococcal Conjugate displays 'Not Started'."
		set vaccineNameRowSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".rowSearchRectangle(vaccineName)
		set firstColumnSearchRectangle to "Immunizations/Forecaster-Common/Helpers".firstcolumnSearchRectangle()
		run "Immunizations/Util/Validation".verifyText vaccineName, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText notStarted, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		
		Log "VERIFICATION: Dose 1 for Pneumococcal Conjugate is displayed in the column dated for patient's DOB + 2 months to DOB + 3 months + 4 weeks - 1 day."
		set startDateHeader to uppercase("Immunizations/Util/Date".adjustDate(dob, format, ("Month":2)))
		set endDateHeader to uppercase("Immunizations/Util/Date".adjustDate(dob, format, ("Month":3,"Week":4, "Day":-1)))
		set alignment to ("Left","Right")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText "Dose 1", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Dose 2 for Pneumococcal Conjugate is displayed in the column dated for patient's DOB + 4 months to DOB + 5 months + 4 weeks - 1 day."
		set startDateHeader to uppercase("Immunizations/Util/Date".adjustDate(dob, format, ("Month":4)))
		set endDateHeader to uppercase("Immunizations/Util/Date".adjustDate(dob, format, ("Month":5,"Week":4, "Day":-1)))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText "Dose 2", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Dose 3 for Pneumococcal Conjugate is displayed in the column dated for patient's DOB + 6 months to DOB + 7 months + 4 weeks - 1 day."
		set startDateHeader to uppercase("Immunizations/Util/Date".adjustDate(dob, format, ("Month":6)))
		set endDateHeader to uppercase("Immunizations/Util/Date".adjustDate(dob, format, ("Month":7,"Week":4, "Day":-1)))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText "Dose 3", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)
		
		Log "VERIFICATION: Dose 4 and 5 for Pneumococcal Conjugate is displayed in the column dated for patient's DOB + 12 months to Dose 4's Recommended Until date + 8 weeks - 1 day (DOB + 16 months + 4 weeks - 1 day + 8 weeks - 1 day)."
		set startDateHeader to uppercase("Immunizations/Util/Date".adjustDate(dob, format, ("Month":12)))
		set dose4RecommendedUntil to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":16, "Week":4, "Day":-1))
		set endDateHeader to uppercase("Immunizations/Util/Date".adjustDate(dose4RecommendedUntil, format, ("Week":8, "Day":-1)))
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText "2 Dose Series", "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)		
		CaptureScreen (Name:"Step"&Global stepNumber&"-Initial Forecast Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Pneumococcal Conjugate within the first column"
		run "Immunizations/Forecaster-Forecast/Actions".clickVaccineName(VaccineName)
		
		Log "VERIFICATION: The Vaccine Name under CDC Schedule expands with the selected vaccine group in focus."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneHeaderSearchRectangle()
		run "Immunizations/Util/Validation".verifyImage "Immunizations/Forecaster-Forecast/ExpandedView/DoseInFocus", rectangle
		
		Log "VERIFICATION: The expanded view left pane header displays 'Not started'."
		run "Immunizations/Util/Validation".verifyText notStarted, rectangle
		
		Log "VERIFICATION: In the left pane, Dose 1 displays 'Not Due Until' with Recommended From Date (DOB + 2 months)."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("1")
		set dose1NewDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":2))
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & dose1NewDate, rectangle
		
		Log "VERIFICATION: In the left pane, Dose 2 displays 'Not Due Until' with Recommended From Date (DOB + 4 months)."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("2")
		set dose2AdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":4))
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & dose2AdminDate, rectangle
		
		Log "VERIFICATION: In the left pane, Dose 3 displays 'Not Due Until' with Recommended From Date (DOB + 6 months)."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("3")
		set dose3AdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":6))
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & dose3AdminDate, rectangle
		
		Log "VERIFICATION: In the left pane, Dose 4 displays 'Not Due Until' with Recommended From Date (DOB + 12 months)."
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("4")
		set dose4AdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":12))
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & dose4AdminDate, rectangle
		
		Log "VERIFICATION: In the left pane, Dose 5 displays 'Not Due Until' with Recommended From Date (+ 8 weeks from Dose 4's Recommended From date (DOB + 12 months + 8 weeks))."
		set dose4RecommendedFrom to dose4AdminDate
		set rectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewLeftPaneDoseSearchrectangle("5")
		run "Immunizations/Util/Validation".verifyText notDueUntil & return & "Immunizations/Util/Date".adjustDate(dose4RecommendedFrom, format, ("Week":8)), rectangle
		
		Log "VERIFICATION: In the right-hand pane 'Not Started – <vaccine group name>' and 'Recommended From' with '< Recommended From Date for Dose 1 - Recommended Until Date for Dose 1 >' is displayed."
		set rightPaneHeaderSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneHeaderSearchRectangle()
		run "Immunizations/Util/Validation".verifyText notStarted && "-" && vaccineName, rightPaneHeaderSearchRectangle
		run "Immunizations/Util/Validation".verifyText earliestRecommendedWithoutColon && "Immunizations/Util/Date".adjustDate(dob, "%m/%d/%y", ("Month":2)) && "-" && "Immunizations/Util/Date".adjustDate(dob, "%m/%d/%y", ("Month":3, "Week":4, "Day":-1)), rightPaneHeaderSearchRectangle
		set expandedViewBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneSearchrectangle()
		run "Immunizations/Util/Validation".verifyText vis, expandedViewBodySearchRectangle
		
		Log "VERIFICATION: Below onto right VIS link is available if any have been configured."
		set expandedViewBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneSearchrectangle()
		run "Immunizations/Util/Validation".verifyText vis, expandedViewBodySearchRectangle
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Header Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Dose 1"
		set doseSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewDoseSearchrectangle()
		click text:"1", searchrectangle:doseSearchRectangle
		
		Log "VERIFICATION: Right-hand pane header displays 'Dose 1'."
		run "Immunizations/Util/Validation".verifyText "Dose 1", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: Date and age for + 6 weeks from DOB"
		set dose1MinimumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Week":6))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose1MinimumDate
		set dose1MinimumAge to "Immunizations/Util/Date".ageCalculator (dob, dose1MinimumDate, false, false)
		set rightPaneBodySearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".expandedViewRightPaneBodySearchRectangle()
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1MinimumAge, "Immunizations/Util/Date".setPattern(dose1MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended From: Date and age for + 2 months from DOB"
		set dose1EarliestRecommendedDate to dose1NewDate
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose1EarliestRecommendedDate
		set dose1EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator (dob, dose1EarliestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose1EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: Date and age for + 3 months + 4 weeks - 1 day from DOB"
		set dose1LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":3, "Week":4, "Day":-1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose1LatestRecommendedDate
		set dose1LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator (dob, dose1LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose1LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION:  Latest: Date and age for + 5 years - 1 day from DOB"
		set doseMaximumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Year":5, "Day":-1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, doseMaximumDate
		set doseMaximumAge to "Immunizations/Util/Date".ageCalculator (dob, doseMaximumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern doseMaximumAge, "Immunizations/Util/Date".setPattern(doseMaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Dose 1 Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Dose 2"
		click text:"2", searchrectangle:doseSearchRectangle
		
		Log "VERIFICATION: Right-hand pane header displays 'Dose 2'."
		run "Immunizations/Util/Validation".verifyText "Dose 2", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: Date and age for + 10 weeks from DOB"
		set dose2MinimumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Week":10))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose2MinimumDate
		set dose2MinimumAge to "Immunizations/Util/Date".ageCalculator(dob, dose2MinimumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2MinimumAge, "Immunizations/Util/Date".setPattern(dose2MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended From: Date and age for + 4 months from DOB"
		set dose2EarliestRecommendedDate to dose2AdminDate
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose2EarliestRecommendedDate
		set dose2EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose2EarliestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose2EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: Date and age for + 5 months + 4 weeks - 1 day from DOB"
		set dose2LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":5, "Week":4, "Day":-1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose2LatestRecommendedDate
		set dose2LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator(dob, dose2LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose2LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose2LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION:  Latest: Date and age for + 5 years - 1 day from DOB"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, doseMaximumDate
		run "Immunizations/Util/Validation".verifyTextWithPattern doseMaximumAge, "Immunizations/Util/Date".setPattern(doseMaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Dose 2 Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Dose 3"
		click text:"3", searchrectangle:doseSearchRectangle
		
		Log "VERIFICATION: Right-hand pane header displays 'Dose 3'."
		run "Immunizations/Util/Validation".verifyText "Dose 3", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: Date and age for + 14 weeks from DOB"
		set dose3MinimumDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Week":14))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose3MinimumDate
		set dose3MinimumAge to "Immunizations/Util/Date".ageCalculator (dob, dose3MinimumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3MinimumAge, "Immunizations/Util/Date".setPattern(dose3MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended From: Date and age for + 6 months from DOB"
		set dose3EarliestRecommendedDate to dose3AdminDate
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose3EarliestRecommendedDate
		set dose3EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator (dob, dose3EarliestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose3EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: Date and age for + 7 months + 4 weeks - 1 day from DOB"
		set dose3LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":7, "Week":4, "Day":-1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose3LatestRecommendedDate
		set dose3LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator (dob, dose3LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose3LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose3LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION:  Latest: Date and age for + 5 years - 1 day from DOB"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, doseMaximumDate
		run "Immunizations/Util/Validation".verifyTextWithPattern doseMaximumAge, "Immunizations/Util/Date".setPattern(doseMaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Dose 3 Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Dose 5" // had to switch order as eggPlant was struggling to see the 5 with cell above highlighting and kept clicking the wrong dose when pulling in validCharacters with autoUpdate.
		click text:"5", searchrectangle:doseSearchRectangle
		
		Log "VERIFICATION: Right-hand pane header displays 'Dose 5'."
		run "Immunizations/Util/Validation".verifyText "Dose 5", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: Date and age for + 8 weeks from Dose 4's Earliest"
		set dose4Earliest to dose4AdminDate
		set dose5MinimumDate to "Immunizations/Util/Date".adjustDate(dose4Earliest, format, ("Week":8))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose5MinimumDate
		set dose5MinimumAge to "Immunizations/Util/Date".ageCalculator (dob, dose5MinimumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose5MinimumAge, "Immunizations/Util/Date".setPattern(dose5MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended From: Date and age for + 8 weeks from Dose 4's Recommended From"
		set dose5EarliestRecommendedDate to "Immunizations/Util/Date".adjustDate(dose4RecommendedFrom, format, ("Week":8))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose5EarliestRecommendedDate
		set dose5EarliestRecommendedAge to "Immunizations/Util/Date".ageCalculator (dob, dose5EarliestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose5EarliestRecommendedAge, "Immunizations/Util/Date".setPattern(dose5EarliestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(earliestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: Date and age for + 8 weeks - 1 day from Dose 4's Recommended Until"
		set dose5LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dose4RecommendedUntil, format, ("Week":8, "Day":-1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose5LatestRecommendedDate
		set dose5LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator (dob, dose5LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose5LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose5LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION:  Latest: Date and age for + 5 years - 1 day from DOB"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, doseMaximumDate
		run "Immunizations/Util/Validation".verifyTextWithPattern doseMaximumAge, "Immunizations/Util/Date".setPattern(doseMaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Dose 5 Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on Dose 4"
		click text:"4", searchrectangle:doseSearchRectangle
		
		Log "VERIFICATION: Right-hand pane header displays 'Dose 4'."
		run "Immunizations/Util/Validation".verifyText "Dose 4", rightPaneHeaderSearchRectangle
		
		Log "VERIFICATION: Earliest: Date and age for + 12 months from DOB"
		set dose4MinimumDate to dose4AdminDate
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField minimum, dose4MinimumDate
		set dose4MinimumAge to "Immunizations/Util/Date".ageCalculator (dob, dose4MinimumDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose4MinimumAge, "Immunizations/Util/Date".setPattern(dose4MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended From: Date and age for + 12 months from DOB"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField earliestRecommended, dose4MinimumDate
		run "Immunizations/Util/Validation".verifyTextWithPattern dose4MinimumAge, "Immunizations/Util/Date".setPattern(dose4MinimumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(minimum, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION: Recommended Until: Date and age for + 16 months + 4 weeks - 1 day from DOB"
		set dose4LatestRecommendedDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Month":16, "Week":4, "Day":-1))
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField latestRecommended, dose4LatestRecommendedDate
		set dose4LatestRecommendedAge to "Immunizations/Util/Date".ageCalculator (dob, dose4LatestRecommendedDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose4LatestRecommendedAge, "Immunizations/Util/Date".setPattern(dose4LatestRecommendedAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(latestRecommended, rightPaneBodySearchRectangle)
		
		Log "VERIFICATION:  Latest: Date and age for + 5 years - 1 day from DOB"
		run "Immunizations/Forecaster-Forecast/Validations".verifyExpandedViewField maximum, doseMaximumDate
		run "Immunizations/Util/Validation".verifyTextWithPattern doseMaximumAge, "Immunizations/Util/Date".setPattern(doseMaximumAge), "Immunizations/Common/Helpers".fieldValueSearchRectangle(maximum, rightPaneBodySearchRectangle)
		CaptureScreen(Name:"Step"&Global stepNumber&"-Expanded View Dose 4 Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click outside expanded view and click on document history button select Pneumococcal Conjugate vaccine from the selected Immunization dialog, click on select button. Enter an administration date of DOB + 6 weeks - 5 days choosing PCV13 (Prevnar CVX133) as the product and fill in all required fields, and click on the Document button."
		Click text:"Print", searchrectangle:"Immunizations/Common/Helpers".tabListSearchrectangle
		set dose1AdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Week":6, "Day":-5))
		run "Immunizations/Common/DocumentHistory/Task".documentWithProduct vaccineName, dateFormat, dose1AdminDate, source, product1, "Submit"
		
		Log "VERIFICATION: The first column for Pneumococcal Conjugate displays 'Last Admin: < DOB + 6 weeks - 5 days >'."
		run "Immunizations/Util/Validation".verifyText vaccineName, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText lastAdmin && dose1AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		set dose1AdminAge to "Immunizations/Util/Date".ageCalculator (dob, dose1AdminDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1AdminAge, "Immunizations/Util/Date".setPattern(dose1AdminAge), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		run "Immunizations/Util/Validation".verifyImage didNotCountImage, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		
		Log "VERIFICATION: The charted administration displays in Immunization Forecaster within the column dated for DOB + 6 weeks - 5 days. The Did Not Count icon with the product name and the administered date is displayed."
		run "Immunizations/Common/Actions".clickImageWithRepeat "4", "Immunizations/Forecaster-Forecast/Search/Icon_ScrollBarLeftArrow" 
		set startDateHeader to uppercase(dose1AdminDate)
		set endDateHeader to uppercase(dose1AdminDate)
		set alignment to ("Center","Center")
		set (topOffset1, topOffset2, bottomOffset1, bottomOffset2) to "Immunizations/Forecaster-Forecast/Helpers".columnHeaderAlignment(alignment)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, topOffset1, topOffset2, bottomOffset1, bottomOffset2)
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText product1, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText dose1AdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyImage didNotCountImage, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)		
		CaptureScreen(Name:"Step"&Global stepNumber&"-Did Not Count 6w-5d Charted Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber & "Navigate back to the mpage and modify the administration date for Pneumococcal Conjugate from the date for DOB + 6 weeks - 5 days to DOB + 6 weeks - 4 days."
		set topPaneRectangle to "Immunizations/Common/Helpers".tabListSearchrectangle
		click text:viewpoint, searchrectangle:topPaneRectangle
		run "Immunizations/WorkflowMPage/Table/Actions".clickVaccineGroupName vaccineName
		set dose1NewAdminDate to "Immunizations/Util/Date".adjustDate(dob, format, ("Week": 6, "day": -4))
		run "Immunizations/WorkFlowMPage/SidePanel/Task".modifyAdminDate dose1AdminDate, "1", dateFormat, dose1NewAdminDate  
		
		Log "VERIFICATION: The administrations column displays '1' for Pneumococcal Conjugate without the did not count icon."
		run "Immunizations/WorkflowMPage/Table/Validations".verifyAdministrationColumn vaccineName, "1", "false"
		CaptureScreen(Name:"Step"&Global stepNumber&"-Mpage Dose 1 Charted Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Click on 'View Forecast'."
		run "Immunizations/WorkflowMPage/Table/Actions".clickViewForecast (viewForecast)
		
		Log "VERIFICATION: The first column for Pneumococcal Conjugate displays 'Last Admin: < DOB + 6 weeks - 4 days >'."
		run "Immunizations/Util/Validation".verifyText vaccineName, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText lastAdmin && dose1NewAdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		set dose1NewAdminAge to "Immunizations/Util/Date".ageCalculator (dob, dose1NewAdminDate, false, false)
		run "Immunizations/Util/Validation".verifyTextWithPattern dose1NewAdminAge, "Immunizations/Util/Date".setPattern(dose1NewAdminAge), "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, firstColumnSearchRectangle)
		
		Log "VERIFICATION: Dose 1 displays in Immunization Forecaster within the column dated for DOB + 6 weeks - 4 days. The Did Not Count icon with the product name and the administered date is displayed."
		run "Immunizations/Common/Actions".clickImageWithRepeat "1", "Immunizations/Forecaster-Forecast/Search/Icon_ScrollBarLeftArrow" 
		set startDateHeader to uppercase(dose1NewAdminDate)
		set endDateHeader to uppercase(dose1NewAdminDate)
		set columnSearchRectangle to "Immunizations/Forecaster-Forecast/Helpers".columnSearchRectangle(startDateHeader, endDateHeader, "-65", "-5", "50", "550")
		run "Immunizations/Forecaster-Forecast/Validations".verifyColumnHeaderAges startDateHeader, endDateHeader, dob
		run "Immunizations/Util/Validation".verifyText product1, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)
		run "Immunizations/Util/Validation".verifyText "Dose 1" && "-" && dose1NewAdminDate, "Immunizations/WorkflowMPage/Table/Helpers".cellIntersection(vaccineNameRowSearchRectangle, columnSearchRectangle)		
		CaptureScreen(Name:"Step"&Global stepNumber&"-Forecast Dose 1 Charted Patient1")
		---------------------------------------------------------------------------------------------------------------		
		Log "Util".stepNumber &"ACTION: Close Application."
		run "Immunizations/setup".closeApplication 
		
		EndTestCase "VR/Pnuemococcal/HLM-VR-Immunizations-Pneumococcal_Standard_Series_Full_Forecast_6_weeks_old"
		---------------------------------------------------------------------------------------------------------------
	catch
		LogError "Patient Workflow Steps Exception encountered: " && the exception.reason
		captureScreen "PWF_Ex" & formattedTime("_%m%d%Y%H%M%S", the time)
	end try
	------------------------------------------------------Patient Cleanup----------------------------------------------
	Log "PATIENT CLEANUP: Open PmLaunch and Rename patient(s) from the test"
	run "Immunizations/PatientCreation".openPMLaunch username, password, domain
	run "Immunizations/PatientCreation".openConversationContinuous conversation
	run "Immunizations/PatientCreation".searchPatient lastName, firstName
	run "Immunizations/PatientCreation".renamePatientSearched newLastName
	run "Util".closeApplication 2
	---------------------------------------------------------------------------------------------------------------
catch
	LogError "Exception encountered" && the exception.reason
	captureScreen"Exception" & formattedTime("_%m%d%Y%H%M%S", the time)
End Try
---------------------------------------------------------------------------------------------------------------

# SUT CLEANUP
run "Cleanup".ZeroStateCloseAllApps	